# Set up
- Import the Libraly
- Declare Identity
- Define a company's name

In [2]:
import pandas as pd

In [2]:
# 1. Import the libraly
from edgar import *

# 2. Declare identity
set_identity("info.pakkaols@gmail.com")

# 3. Find a company 
company = Company('AAPL') # Apple Inc

# 4. Get company filings
filings = company.get_filings()

# Get overview of the company

In [3]:
company

╭────────────────────────────────────────────── 🏢 Apple Inc. AAPL ───────────────────────────────────────────────╮
│                                                                                                                 │
│                                                                                                                 │
│ ╭───────────────────────────────────────────────── 📋 Entity ─────────────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   CIK   320193   Type   Operating   ○                                                                       │ │
│ │                                                                                                             │ │
│ │                                                                                                             │ │
│ │   Category                  Industry                     Fiscal Year End                                    │ │
│ │  ────────────────────────────────────────────────────────────────────────                                   │ │
│ │   Large accelerated filer   3571: Electronic Computers   Sep 27                                             │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ ╭─────────────────────────────────────────────── 📈 Exchanges ────────────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   Exchange   Symbol                                                                                         │ │
│ │  ───────────────────                                                                                        │ │
│ │   Nasdaq     AAPL                                                                                           │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ ╭─── 🏢 Business Address ────╮      ╭──── 📫 Mailing Address ────╮     ╭── 📞 Contact Information ──╮           │
│ │ ONE APPLE PARK WAY         │      │ ONE APPLE PARK WAY         │     │                            │           │
│ │ CUPERTINO, CA 95014        │      │ CUPERTINO, CA 95014        │     │   Phone   (408) 996-1010   │           │
│ ╰────────────────────────────╯      ╰────────────────────────────╯     │                            │           │
│                                                                        ╰────────────────────────────╯           │
│ ╭────────────────────────────────────────────── 📜 Former Names ──────────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   APPLE INC                January 2007 to August 2019                                                      │ │
│ │   APPLE COMPUTER INC       January 1994 to January 2007                                                     │ │
│ │   APPLE COMPUTER INC/ FA   July 1997 to July 1997                                                           │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────── SEC Entity Data ────────────────────────────────────────────────╯

## Primarily investigate filing types by this company

In [4]:
filings

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│                                                                              Filing                             │
│    Form        Description                                                   Date         Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    4           Statement of changes in beneficial ownership                  2025-08-29   0001214128-25-0000…   │
│    144         Notice of proposed sale                                       2025-08-28   0001921094-25-0010…   │
│    4           Statement of changes in beneficial ownership                  2025-08-27   0001631982-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-08-12   0001767094-25-0000…   │
│    144         Notice of proposed sale                                       2025-08-08   0001969223-25-0005…   │
│    10-Q        Quarterly report for public companies                         2025-08-01   0000320193-25-0000…   │
│    8-K         Current report                                                2025-07-31   0000320193-25-0000…   │
│    SCHEDULE    Beneficial ownership by passive investors/institutions        2025-07-29   0000932471-25-0007…   │
│    13G/A                                                                                                        │
│    3           Initial statement of beneficial ownership                     2025-07-25   0000320193-25-0000…   │
│    8-K         Current report                                                2025-07-25   0001140361-25-0273…   │
│    8-K         Current report                                                2025-07-09   0001140361-25-0252…   │
│    25-NSE      Notice of matured/redeemed/retired securities by exchanges    2025-05-22   0001354457-25-0004…   │
│    4           Statement of changes in beneficial ownership                  2025-05-14   0000320193-25-0000…   │
│    8-K         Current report                                                2025-05-12   0001140361-25-0184…   │
│    424B2       Primary offering prospectus                                   2025-05-06   0001140361-25-0175…   │
│    FWP         Filing of free writing prospectuses                           2025-05-06   0001140361-25-0174…   │
│    424B2       Primary offering prospectus                                   2025-05-05   0001140361-25-0172…   │
│    10-Q        Quarterly report for public companies                         2025-05-02   0000320193-25-0000…   │
│    8-K         Current report                                                2025-05-01   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-25   0000320193-25-0000…   │
│    144         Notice of proposed sale                                       2025-04-23   0001950047-25-0025…   │
│    4           Statement of changes in beneficial ownership                  2025-04-17   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-17   0000320193-25-0000…   │
│    SD          Specialized disclosure report on conflict minerals or         2025-04-04   0001140361-25-0123…   │
│                resource extraction payments                                                                     │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    144         Notice of proposed sale                                       2025-04-02   0001950047-25-0023…   │
│    144         Notice of proposed sale                                       2025-04-02   0001969223-25-0002…   │
│    144         Notice of proposed sale                                       2025-04-02   0001959173-25-0024…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    8-K         Current report                                                2025-02-25   0001140361-25-0058…   │
│    PX14A6G     Exempt solicitation                                           2025-02-13   0001096906-25-0001…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    144         Notice of proposed sale                                       2025-02-03   0001921094-25-0000…   │
│    10-Q        Quarterly report for public companies                         2025-01-31   0000320193-25-0000…   │
│    8-K         Current report                                                2025-01-30   0000320193-25-0000…   │
│                                                                                                                 │
│                                                                                                                 │
│                                                                                                                 │
│ Showing 1 to 50 of 2,164 filings. Page using ← prev() and next() →                                              │
╰─────────────────────────────── Company filings between 1994-01-26 and 2025-08-29 ───────────────────────────────╯

## We will be focusing on the anuual and quarterly reports (10-K and 10-Q).

In [5]:
# 5. Filter by form 

# See samples of quarter filings
quater_filings = filings.filter(form="10-K")  # Insider transactions
quater_filings.sample(5)

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│                                                                              Filing                             │
│    Form        Description                                                   Date         Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    10-K        Annual report for public companies                            2022-10-28   0000320193-22-0001…   │
│    10-K        Annual report for public companies                            2021-10-29   0000320193-21-0001…   │
│    10-K        Annual report for public companies                            2020-10-30   0000320193-20-0000…   │
│    10-K        Annual report for public companies                            2011-10-26   0001193125-11-2821…   │
│    10-K        Annual report for public companies                            1995-12-19   0000320193-95-0000…   │
│                                                                                                                 │
╰─────────────────────────────── Company filings between 1995-12-19 and 2022-10-28 ───────────────────────────────╯

In [43]:
quater_filings = filings.filter(form="10-K")  # Insider transactions
quater_filings

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│                                                                              Filing                             │
│    Form        Description                                                   Date         Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    10-K        Annual report for public companies                            2024-11-01   0000320193-24-0001…   │
│    10-K        Annual report for public companies                            2023-11-03   0000320193-23-0001…   │
│    10-K        Annual report for public companies                            2022-10-28   0000320193-22-0001…   │
│    10-K        Annual report for public companies                            2021-10-29   0000320193-21-0001…   │
│    10-K        Annual report for public companies                            2020-10-30   0000320193-20-0000…   │
│    10-K        Annual report for public companies                            2019-10-31   0000320193-19-0001…   │
│    10-K        Annual report for public companies                            2018-11-05   0000320193-18-0001…   │
│    10-K        Annual report for public companies                            2017-11-03   0000320193-17-0000…   │
│    10-K        Annual report for public companies                            2016-10-26   0001628280-16-0203…   │
│    10-K        Annual report for public companies                            2015-10-28   0001193125-15-3563…   │
│    10-K        Annual report for public companies                            2014-10-27   0001193125-14-3834…   │
│    10-K        Annual report for public companies                            2013-10-30   0001193125-13-4165…   │
│    10-K        Annual report for public companies                            2012-10-31   0001193125-12-4440…   │
│    10-K        Annual report for public companies                            2011-10-26   0001193125-11-2821…   │
│    10-K        Annual report for public companies                            2010-10-27   0001193125-10-2380…   │
│    10-K        Annual report for public companies                            2009-10-27   0001193125-09-2148…   │
│    10-K        Annual report for public companies                            2008-11-05   0001193125-08-2249…   │
│    10-K        Annual report for public companies                            2007-11-15   0001047469-07-0093…   │
│    10-K        Annual report for public companies                            2006-12-29   0001104659-06-0842…   │
│    10-K        Annual report for public companies                            2005-12-01   0001104659-05-0584…   │
│    10-K        Annual report for public companies                            2004-12-03   0001047469-04-0359…   │
│    10-K        Annual report for public companies                            2003-12-19   0001047469-03-0416…   │
│    10-K        Annual report for public companies                            2002-12-19   0001047469-02-0076…   │
│    10-K        Annual report for public companies                            2000-12-14   0000912057-00-0536…   │
│    10-K        Annual report for public companies                            1999-12-22   0000912057-99-0102…   │
│    10-K        Annual report for public companies                            1997-12-05   0001047469-97-0069…   │
│    10-K        Annual report for public companies                            1996-12-19   0000320193-96-0000…   │
│    10-K        Annual report for public companies                            1995-12-19   0000320193-95-0000…   │
│    10-K        Annual report for public companies                            1994-12-13   0000320193-94-0000…   │
│                                                                                                                 │
╰─────────────────────────────── Company filings between 1994-12-13 and 2024-11-01 ───────────────────────────────╯

In [6]:
# See the sample of annual filings
annual_filings = filings.filter(form="10-Q")
annual_filings.sample(5)

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│                                                                              Filing                             │
│    Form        Description                                                   Date         Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    10-Q        Quarterly report for public companies                         2024-08-02   0000320193-24-0000…   │
│    10-Q        Quarterly report for public companies                         2010-07-21   0001193125-10-1628…   │
│    10-Q        Quarterly report for public companies                         2006-02-03   0001104659-06-0059…   │
│    10-Q        Quarterly report for public companies                         2000-07-31   0000912057-00-0339…   │
│    10-Q        Quarterly report for public companies                         2000-02-01   0000912057-00-0032…   │
│                                                                                                                 │
╰─────────────────────────────── Company filings between 2000-02-01 and 2024-08-02 ───────────────────────────────╯

## Get meta data of the filings

In [18]:
quater_filings.to_pandas().sample(5)

,accession_number,filing_date,reportDate,acceptanceDateTime,act,form,fileNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription
13,0001193125-11-282113,2011-10-26,2011-09-24,2011-10-26 20:35:25+00:00,34,10-K,000-10030,,9435428,1,0,d220209d10k.htm,FORM 10-K
19,0001104659-05-058421,2005-12-01,2005-09-24,2005-12-01 02:22:48+00:00,34,10-K,000-10030,,3185770,0,0,a05-20674_110k.htm,ANNUAL REPORT PURSUANT TO SECTION 13 AND 15(D)
28,0000320193-94-000016,1994-12-13,1994-09-30,1994-12-13 05:00:00+00:00,,10-K,000-10030,,240556,0,0,,
4,0000320193-20-000096,2020-10-30,2020-09-26,2020-10-29 22:06:25+00:00,34,10-K,001-36743,,12502600,1,1,aapl-20200926.htm,10-K
6,0000320193-18-000145,2018-11-05,2018-09-29,2018-11-05 13:01:40+00:00,34,10-K,001-36743,,12275572,1,0,a10-k20189292018.htm,10-K

In [17]:
annual_filings.to_pandas().sample(5)

,accession_number,filing_date,reportDate,acceptanceDateTime,act,form,fileNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription
1,0000320193-25-000057,2025-05-02,2025-03-29,2025-05-02 10:00:46+00:00,34,10-Q,001-36743,,5299807,1,1,aapl-20250329.htm,10-Q
85,0000320193-97-000011,1997-05-12,1997-03-28,1997-05-12 04:00:00+00:00,,10-Q,000-10030,,234224,0,0,,
60,0001104659-05-035792,2005-08-03,2005-06-25,2005-08-03 00:15:08+00:00,34,10-Q,000-10030,,1460540,0,0,a05-12535_110q.htm,10-Q
38,0001193125-13-022339,2013-01-24,2012-12-29,2013-01-24 22:01:37+00:00,34,10-Q,000-10030,,5826231,1,0,d453687d10q.htm,FORM 10-Q
76,0000912057-00-023442,2000-05-11,2000-04-01,2000-05-11 04:00:00+00:00,,10-Q,000-10030,,172724,0,0,,10-Q

## Load the 10-K filings

In [29]:
ten_k_filings = get_filings(form='10-K') # Get company filings by form
ten_k_filing = ten_k_filings[0] # Access to the filing no. 1
ten_k_report = ten_k_filing.obj() # Get and parse filing data object

## Access Financial Statements

In [25]:
financial_data = ten_k_report.financials # Get the company's financials
financial_data

╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│                   Entity Information                                                                            │
│                                                                                                                 │
│   Property                   Value                                                                              │
│  ─────────────────────────────────────────────────────                                                          │
│   entity_name                EVOLUTION PETROLEUM CORP                                                           │
│   ticker                     EPM                                                                                │
│   identifier                 1006655                                                                            │
│   document_type              10-K                                                                               │
│   reporting_end_date         2025-09-12                                                                         │
│   document_period_end_date   2025-06-30                                                                         │
│   fiscal_year                2025                                                                               │
│   fiscal_period              FY                                                                                 │
│   fiscal_year_end_month      6                                                                                  │
│   fiscal_year_end_day        30                                                                                 │
│   annual_report              True                                                                               │
│   quarterly_report           False                                                                              │
│   amendment                  False                                                                              │
│                                                                                                                 │
│                                              Financial Statements                                               │
│                                                                                                                 │
│   Type                        Definition                                                             Elements   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   CoverPage                   DocumentCoverPage                                                      40         │
│   BalanceSheet                StatementConsolidatedBalanceSheets                                     34         │
│   BalanceSheetParenthetical   StatementConsolidatedBalanceSheetsParenthetical                        5          │
│   IncomeStatement             StatementConsolidatedStatementsOfOperations                            29         │
│   CashFlowStatement           StatementConsolidatedStatementsOfCashFlows                             41         │
│   StatementOfEquity           StatementConsolidatedStatementsOfChangesInStockholdersEquity           24         │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPolicies              2          │
│   Disclosures                 DisclosureRevenueRecognition                                           2          │
│   Disclosures                 DisclosureAcquisitions                                                 2          │
│   Disclosures                 DisclosurePropertyAndEquipment                                         2          │
│   Disclosures                 DisclosureSeniorSecuredCreditFacility                                  2          │
│   Disclosures                 DisclosureIncomeTaxes                                                  2          │
│   Disclosures                 DisclosureDerivatives                                                  2          │
│   Disclosures                 DisclosureFairValueMeasurement                                         2          │
│   Disclosures                 DisclosureAssetRetirementObligations                                   2          │
│   Disclosures                 DisclosureCommitmentsAndContingencies                                  2          │
│   Disclosures                 DisclosureStockholdersEquity                                           2          │
│   Disclosures                 DisclosureEarningsLossPerCommonShare                                   2          │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformation                      2          │
│   Disclosures                 DisclosureSubsequentEvents                                             2          │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesPolicies      18         │
│   Disclosures                 DisclosureRevenueRecognitionTables                                     2          │
│   Disclosures                 DisclosurePropertyAndEquipmentTables                                   2          │
│   Disclosures                 DisclosureIncomeTaxesTables                                            4          │
│   Disclosures                 DisclosureDerivativesTables                                            6          │
│   Disclosures                 DisclosureFairValueMeasurementTables                                   3          │
│   Disclosures                 DisclosureAssetRetirementObligationsTables                             2          │
│   Disclosures                 DisclosureStockholdersEquityTables                                     11         │
│   Disclosures                 DisclosureEarningsLossPerCommonShareTables                             2          │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformationTables                2          │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesNatureOfOp…   2          │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesDetails       23         │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesConcentrat…   16         │
│   Disclosures                 DisclosureRevenueRecognitionRevenuesByMajorProductDetails              9          │
│   Disclosures                 DisclosureRevenueRecognitionDetails                                    9          │
│   Disclosures                 DisclosureAcquisitionsDetails                                          33         │
│   Disclosures                 DisclosurePropertyAndEquipmentOtherDetails                             5          │
│   Disclosures                 DisclosurePropertyAndEquipmentDetails                                  17         │
│   Disclosures                 DisclosureSeniorSecuredCreditFacilityDetails                           46         │
│   Disclosures                 DisclosureIncomeTaxesDetails                                           16         │
│   Disclosures                 DisclosureIncomeTaxesComponentsOfIncomeTaxExpenseBenefitDetails        10         │
│   Disclosures                 DisclosureIncomeTaxesReconciliationOfStatutoryAndIncomeTaxExpenseDe…   21         │
│   Disclosures                 DisclosureIncomeTaxesScheduleOfDeferredIncomeTaxesDetails              13         │
│   Disclosures                 DisclosureDerivativesConsolidatedBalanceSheetsDetails                  15         │
│   Disclosures                 DisclosureDerivativesGainAndLossOnDerivativesDetails                   4          │
│   Disclosures                 DisclosureDerivativesCrudeOilDerivativePositionsDetails                41         │
│   Disclosures                 DisclosureDerivativesDerivativeContractsDetails                        7          │
│   Disclosures                 DisclosureFairValueMeasurementFinancialAssetsAndLiabilitiesDetails     8          │
│   Disclosures                 DisclosureAssetRetirementObligationsSummaryOfAssetRetirementObligat…   10         │
│   Disclosures                 DisclosureStockholdersEquityNarrativeDetails                           33         │
│   Disclosures                 DisclosureStockholdersEquityDividendsDetails                           14         │
│   Disclosures                 DisclosureStockholdersEquityTreasurySharesDetails                      9          │
│   Disclosures                 DisclosureStockholdersEquityStockBasedIncentivePlanNarrativeDetails    28         │
│   Disclosures                 DisclosureStockholdersEquityFairValueAssumptionsDetails                6          │
│   Disclosures                 DisclosureStockholdersEquityScheduleOfRestrictedStockAndContingentR…   26         │
│   Disclosures                 DisclosureEarningsLossPerCommonShareScheduleOfBasicAndDilutedEarnin…   13         │
│   Disclosures                 DisclosureEarningsLossPerCommonShareScheduleOfOutstandingPotentiall…   7          │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformationConsolidatedBalanc…   28         │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformationDetails               7          │
│   Disclosures                 DisclosureSubsequentEventsDetails                                      20         │
│                                                                                                                 │
│      Facts Summary                                                                                              │
│                                                                                                                 │
│   Category      Count                                                                                           │
│  ─────────────────────                                                                                          │
│   Total Facts   789                                                                                             │
│   Contexts      172                                                                                             │
│   Units         14                                                                                              │
│   Elements      584                                                                                             │
│                                                                                                                 │
│            Reporting Periods                                                                                    │
│                                                                                                                 │
│   Type       Period                                                                                             │
│  ─────────────────────────────────────                                                                          │
│   Duration   2025-07-01 to 2025-09-15                                                                           │
│   Instant    2025-09-12                                                                                         │
│   Duration   2025-08-04 to 2025-08-04                                                                           │
│   Instant    2025-07-31                                                                                         │
│   Duration   2025-07-01 to 2025-07-31                                                                           │
│   Instant    2025-07-01                                                                                         │
│   Duration   2025-07-01 to 2025-07-01                                                                           │
│   Instant    2025-06-30                                                                                         │
│   Duration   2024-07-01 to 2025-06-30                                                                           │
│   Duration   2014-01-01 to 2025-06-30                                                                           │
│   Duration   2025-06-30 to 2025-06-30                                                                           │
│   Duration   2025-04-01 to 2025-06-30                                                                           │
│   Instant    2025-04-14                                                                                         │
│   Duration   2025-04-14 to 2025-04-14                                                                           │
│   Duration   2025-01-01 to 2025-03-31                                                                           │
│   Instant    2025-03-07                                                                                         │
│   Instant    2024-12-31                                                                                         │
│   Duration   2022-09-08 to 2024-12-31                                                                           │
│   Duration   2024-10-01 to 2024-12-31                                                                           │
│   Instant    2024-12-05                                                                                         │
│   Duration   2024-12-05 to 2024-12-05                                                                           │
│   Instant    2024-12-04                                                                                         │
│   Instant    2024-10-21                                                                                         │
│   Duration   2024-07-01 to 2024-09-30                                                                           │
│   Instant    2024-06-30                                                                                         │
│   Duration   2023-07-01 to 2024-06-30                                                                           │
│   Duration   2024-04-01 to 2024-06-30                                                                           │
│   Duration   2023-11-01 to 2024-06-30                                                                           │
│   Duration   2024-01-01 to 2024-03-31                                                                           │
│   Instant    2024-02-12                                                                                         │
│   Duration   2024-02-12 to 2024-02-12                                                                           │
│   Duration   2023-10-01 to 2023-12-31                                                                           │
│   Duration   2023-07-01 to 2023-09-30                                                                           │
│   Instant    2023-09-12                                                                                         │
│   Instant    2023-06-30                                                                                         │
│   Instant    2022-09-08                                                                                         │
│   Instant    2016-04-11                                                                                         │
│   Duration   2016-04-11 to 2016-04-11                                                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

## Explore Financial Data

In [26]:
# Access the income statement
income_statement = financial_data.income_statement

# Access the balance sheet
balance_sheet = financial_data.balance_sheet

# Access the statement of cash flows
cash_flow = financial_data.cashflow_statement()

## Display the data

In [13]:
print(income_statement)

<bound method Financials.income_statement of ╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│                   Entity Information                                                                            │
│                                                                                                                 │
│   Property                   Value                                                                              │
│  ─────────────────────────────────────────────────────                                                          │
│   entity_name                EVOLUTION PETROLEUM CORP                                                           │
│   ticker                     EPM                                                                                │
│   identifier                 1006655                                                                            │
│   document_type              10-K                                                                               │
│   reporting_end_date         2025-09-12                                                                         │
│   document_period_end_date   2025-06-30                                                                         │
│   fiscal_year                2025                                                                               │
│   fiscal_period              FY                                                                                 │
│   fiscal_year_end_month      6                                                                                  │
│   fiscal_year_end_day        30                                                                                 │
│   annual_report              True                                                                               │
│   quarterly_report           False                                                                              │
│   amendment                  False                                                                              │
│                                                                                                                 │
│                                              Financial Statements                                               │
│                                                                                                                 │
│   Type                        Definition                                                             Elements   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   CoverPage                   DocumentCoverPage                                                      40         │
│   BalanceSheet                StatementConsolidatedBalanceSheets                                     34         │
│   BalanceSheetParenthetical   StatementConsolidatedBalanceSheetsParenthetical                        5          │
│   IncomeStatement             StatementConsolidatedStatementsOfOperations                            29         │
│   CashFlowStatement           StatementConsolidatedStatementsOfCashFlows                             41         │
│   StatementOfEquity           StatementConsolidatedStatementsOfChangesInStockholdersEquity           24         │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPolicies              2          │
│   Disclosures                 DisclosureRevenueRecognition                                           2          │
│   Disclosures                 DisclosureAcquisitions                                                 2          │
│   Disclosures                 DisclosurePropertyAndEquipment                                         2          │
│   Disclosures                 DisclosureSeniorSecuredCreditFacility                                  2          │
│   Disclosures                 DisclosureIncomeTaxes                                                  2          │
│   Disclosures                 DisclosureDerivatives                                                  2          │
│   Disclosures                 DisclosureFairValueMeasurement                                         2          │
│   Disclosures                 DisclosureAssetRetirementObligations                                   2          │
│   Disclosures                 DisclosureCommitmentsAndContingencies                                  2          │
│   Disclosures                 DisclosureStockholdersEquity                                           2          │
│   Disclosures                 DisclosureEarningsLossPerCommonShare                                   2          │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformation                      2          │
│   Disclosures                 DisclosureSubsequentEvents                                             2          │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesPolicies      18         │
│   Disclosures                 DisclosureRevenueRecognitionTables                                     2          │
│   Disclosures                 DisclosurePropertyAndEquipmentTables                                   2          │
│   Disclosures                 DisclosureIncomeTaxesTables                                            4          │
│   Disclosures                 DisclosureDerivativesTables                                            6          │
│   Disclosures                 DisclosureFairValueMeasurementTables                                   3          │
│   Disclosures                 DisclosureAssetRetirementObligationsTables                             2          │
│   Disclosures                 DisclosureStockholdersEquityTables                                     11         │
│   Disclosures                 DisclosureEarningsLossPerCommonShareTables                             2          │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformationTables                2          │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesNatureOfOp…   2          │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesDetails       23         │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesConcentrat…   16         │
│   Disclosures                 DisclosureRevenueRecognitionRevenuesByMajorProductDetails              9          │
│   Disclosures                 DisclosureRevenueRecognitionDetails                                    9          │
│   Disclosures                 DisclosureAcquisitionsDetails                                          33         │
│   Disclosures                 DisclosurePropertyAndEquipmentOtherDetails                             5          │
│   Disclosures                 DisclosurePropertyAndEquipmentDetails                                  17         │
│   Disclosures                 DisclosureSeniorSecuredCreditFacilityDetails                           46         │
│   Disclosures                 DisclosureIncomeTaxesDetails                                           16         │
│   Disclosures                 DisclosureIncomeTaxesComponentsOfIncomeTaxExpenseBenefitDetails        10         │
│   Disclosures                 DisclosureIncomeTaxesReconciliationOfStatutoryAndIncomeTaxExpenseDe…   21         │
│   Disclosures                 DisclosureIncomeTaxesScheduleOfDeferredIncomeTaxesDetails              13         │
│   Disclosures                 DisclosureDerivativesConsolidatedBalanceSheetsDetails                  15         │
│   Disclosures                 DisclosureDerivativesGainAndLossOnDerivativesDetails                   4          │
│   Disclosures                 DisclosureDerivativesCrudeOilDerivativePositionsDetails                41         │
│   Disclosures                 DisclosureDerivativesDerivativeContractsDetails                        7          │
│   Disclosures                 DisclosureFairValueMeasurementFinancialAssetsAndLiabilitiesDetails     8          │
│   Disclosures                 DisclosureAssetRetirementObligationsSummaryOfAssetRetirementObligat…   10         │
│   Disclosures                 DisclosureStockholdersEquityNarrativeDetails                           33         │
│   Disclosures                 DisclosureStockholdersEquityDividendsDetails                           14         │
│   Disclosures                 DisclosureStockholdersEquityTreasurySharesDetails                      9          │
│   Disclosures                 DisclosureStockholdersEquityStockBasedIncentivePlanNarrativeDetails    28         │
│   Disclosures                 DisclosureStockholdersEquityFairValueAssumptionsDetails                6          │
│   Disclosures                 DisclosureStockholdersEquityScheduleOfRestrictedStockAndContingentR…   26         │
│   Disclosures                 DisclosureEarningsLossPerCommonShareScheduleOfBasicAndDilutedEarnin…   13         │
│   Disclosures                 DisclosureEarningsLossPerCommonShareScheduleOfOutstandingPotentiall…   7          │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformationConsolidatedBalanc…   28         │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformationDetails               7          │
│   Disclosures                 DisclosureSubsequentEventsDetails                                      20         │
│                                                                                                                 │
│      Facts Summary                                                                                              │
│                                                                                                                 │
│   Category      Count                                                                                           │
│  ─────────────────────                                                                                          │
│   Total Facts   789                                                                                             │
│   Contexts      172                                                                                             │
│   Units         14                                                                                              │
│   Elements      584                                                                                             │
│                                                                                                                 │
│            Reporting Periods                                                                                    │
│                                                                                                                 │
│   Type       Period                                                                                             │
│  ─────────────────────────────────────                                                                          │
│   Duration   2025-07-01 to 2025-09-15                                                                           │
│   Instant    2025-09-12                                                                                         │
│   Duration   2025-08-04 to 2025-08-04                                                                           │
│   Instant    2025-07-31                                                                                         │
│   Duration   2025-07-01 to 2025-07-31                                                                           │
│   Instant    2025-07-01                                                                                         │
│   Duration   2025-07-01 to 2025-07-01                                                                           │
│   Instant    2025-06-30                                                                                         │
│   Duration   2024-07-01 to 2025-06-30                                                                           │
│   Duration   2014-01-01 to 2025-06-30                                                                           │
│   Duration   2025-06-30 to 2025-06-30                                                                           │
│   Duration   2025-04-01 to 2025-06-30                                                                           │
│   Instant    2025-04-14                                                                                         │
│   Duration   2025-04-14 to 2025-04-14                                                                           │
│   Duration   2025-01-01 to 2025-03-31                                                                           │
│   Instant    2025-03-07                                                                                         │
│   Instant    2024-12-31                                                                                         │
│   Duration   2022-09-08 to 2024-12-31                                                                           │
│   Duration   2024-10-01 to 2024-12-31                                                                           │
│   Instant    2024-12-05                                                                                         │
│   Duration   2024-12-05 to 2024-12-05                                                                           │
│   Instant    2024-12-04                                                                                         │
│   Instant    2024-10-21                                                                                         │
│   Duration   2024-07-01 to 2024-09-30                                                                           │
│   Instant    2024-06-30                                                                                         │
│   Duration   2023-07-01 to 2024-06-30                                                                           │
│   Duration   2024-04-01 to 2024-06-30                                                                           │
│   Duration   2023-11-01 to 2024-06-30                                                                           │
│   Duration   2024-01-01 to 2024-03-31                                                                           │
│   Instant    2024-02-12                                                                                         │
│   Duration   2024-02-12 to 2024-02-12                                                                           │
│   Duration   2023-10-01 to 2023-12-31                                                                           │
│   Duration   2023-07-01 to 2023-09-30                                                                           │
│   Instant    2023-09-12                                                                                         │
│   Instant    2023-06-30                                                                                         │
│   Instant    2022-09-08                                                                                         │
│   Instant    2016-04-11                                                                                         │
│   Duration   2016-04-11 to 2016-04-11                                                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>

In [14]:
print(balance_sheet)

<bound method Financials.balance_sheet of ╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│                   Entity Information                                                                            │
│                                                                                                                 │
│   Property                   Value                                                                              │
│  ─────────────────────────────────────────────────────                                                          │
│   entity_name                EVOLUTION PETROLEUM CORP                                                           │
│   ticker                     EPM                                                                                │
│   identifier                 1006655                                                                            │
│   document_type              10-K                                                                               │
│   reporting_end_date         2025-09-12                                                                         │
│   document_period_end_date   2025-06-30                                                                         │
│   fiscal_year                2025                                                                               │
│   fiscal_period              FY                                                                                 │
│   fiscal_year_end_month      6                                                                                  │
│   fiscal_year_end_day        30                                                                                 │
│   annual_report              True                                                                               │
│   quarterly_report           False                                                                              │
│   amendment                  False                                                                              │
│                                                                                                                 │
│                                              Financial Statements                                               │
│                                                                                                                 │
│   Type                        Definition                                                             Elements   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   CoverPage                   DocumentCoverPage                                                      40         │
│   BalanceSheet                StatementConsolidatedBalanceSheets                                     34         │
│   BalanceSheetParenthetical   StatementConsolidatedBalanceSheetsParenthetical                        5          │
│   IncomeStatement             StatementConsolidatedStatementsOfOperations                            29         │
│   CashFlowStatement           StatementConsolidatedStatementsOfCashFlows                             41         │
│   StatementOfEquity           StatementConsolidatedStatementsOfChangesInStockholdersEquity           24         │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPolicies              2          │
│   Disclosures                 DisclosureRevenueRecognition                                           2          │
│   Disclosures                 DisclosureAcquisitions                                                 2          │
│   Disclosures                 DisclosurePropertyAndEquipment                                         2          │
│   Disclosures                 DisclosureSeniorSecuredCreditFacility                                  2          │
│   Disclosures                 DisclosureIncomeTaxes                                                  2          │
│   Disclosures                 DisclosureDerivatives                                                  2          │
│   Disclosures                 DisclosureFairValueMeasurement                                         2          │
│   Disclosures                 DisclosureAssetRetirementObligations                                   2          │
│   Disclosures                 DisclosureCommitmentsAndContingencies                                  2          │
│   Disclosures                 DisclosureStockholdersEquity                                           2          │
│   Disclosures                 DisclosureEarningsLossPerCommonShare                                   2          │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformation                      2          │
│   Disclosures                 DisclosureSubsequentEvents                                             2          │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesPolicies      18         │
│   Disclosures                 DisclosureRevenueRecognitionTables                                     2          │
│   Disclosures                 DisclosurePropertyAndEquipmentTables                                   2          │
│   Disclosures                 DisclosureIncomeTaxesTables                                            4          │
│   Disclosures                 DisclosureDerivativesTables                                            6          │
│   Disclosures                 DisclosureFairValueMeasurementTables                                   3          │
│   Disclosures                 DisclosureAssetRetirementObligationsTables                             2          │
│   Disclosures                 DisclosureStockholdersEquityTables                                     11         │
│   Disclosures                 DisclosureEarningsLossPerCommonShareTables                             2          │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformationTables                2          │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesNatureOfOp…   2          │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesDetails       23         │
│   Disclosures                 DisclosureSummaryOfSignificantEventsAndAccountingPoliciesConcentrat…   16         │
│   Disclosures                 DisclosureRevenueRecognitionRevenuesByMajorProductDetails              9          │
│   Disclosures                 DisclosureRevenueRecognitionDetails                                    9          │
│   Disclosures                 DisclosureAcquisitionsDetails                                          33         │
│   Disclosures                 DisclosurePropertyAndEquipmentOtherDetails                             5          │
│   Disclosures                 DisclosurePropertyAndEquipmentDetails                                  17         │
│   Disclosures                 DisclosureSeniorSecuredCreditFacilityDetails                           46         │
│   Disclosures                 DisclosureIncomeTaxesDetails                                           16         │
│   Disclosures                 DisclosureIncomeTaxesComponentsOfIncomeTaxExpenseBenefitDetails        10         │
│   Disclosures                 DisclosureIncomeTaxesReconciliationOfStatutoryAndIncomeTaxExpenseDe…   21         │
│   Disclosures                 DisclosureIncomeTaxesScheduleOfDeferredIncomeTaxesDetails              13         │
│   Disclosures                 DisclosureDerivativesConsolidatedBalanceSheetsDetails                  15         │
│   Disclosures                 DisclosureDerivativesGainAndLossOnDerivativesDetails                   4          │
│   Disclosures                 DisclosureDerivativesCrudeOilDerivativePositionsDetails                41         │
│   Disclosures                 DisclosureDerivativesDerivativeContractsDetails                        7          │
│   Disclosures                 DisclosureFairValueMeasurementFinancialAssetsAndLiabilitiesDetails     8          │
│   Disclosures                 DisclosureAssetRetirementObligationsSummaryOfAssetRetirementObligat…   10         │
│   Disclosures                 DisclosureStockholdersEquityNarrativeDetails                           33         │
│   Disclosures                 DisclosureStockholdersEquityDividendsDetails                           14         │
│   Disclosures                 DisclosureStockholdersEquityTreasurySharesDetails                      9          │
│   Disclosures                 DisclosureStockholdersEquityStockBasedIncentivePlanNarrativeDetails    28         │
│   Disclosures                 DisclosureStockholdersEquityFairValueAssumptionsDetails                6          │
│   Disclosures                 DisclosureStockholdersEquityScheduleOfRestrictedStockAndContingentR…   26         │
│   Disclosures                 DisclosureEarningsLossPerCommonShareScheduleOfBasicAndDilutedEarnin…   13         │
│   Disclosures                 DisclosureEarningsLossPerCommonShareScheduleOfOutstandingPotentiall…   7          │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformationConsolidatedBalanc…   28         │
│   Disclosures                 DisclosureAdditionalFinancialStatementInformationDetails               7          │
│   Disclosures                 DisclosureSubsequentEventsDetails                                      20         │
│                                                                                                                 │
│      Facts Summary                                                                                              │
│                                                                                                                 │
│   Category      Count                                                                                           │
│  ─────────────────────                                                                                          │
│   Total Facts   789                                                                                             │
│   Contexts      172                                                                                             │
│   Units         14                                                                                              │
│   Elements      584                                                                                             │
│                                                                                                                 │
│            Reporting Periods                                                                                    │
│                                                                                                                 │
│   Type       Period                                                                                             │
│  ─────────────────────────────────────                                                                          │
│   Duration   2025-07-01 to 2025-09-15                                                                           │
│   Instant    2025-09-12                                                                                         │
│   Duration   2025-08-04 to 2025-08-04                                                                           │
│   Instant    2025-07-31                                                                                         │
│   Duration   2025-07-01 to 2025-07-31                                                                           │
│   Instant    2025-07-01                                                                                         │
│   Duration   2025-07-01 to 2025-07-01                                                                           │
│   Instant    2025-06-30                                                                                         │
│   Duration   2024-07-01 to 2025-06-30                                                                           │
│   Duration   2014-01-01 to 2025-06-30                                                                           │
│   Duration   2025-06-30 to 2025-06-30                                                                           │
│   Duration   2025-04-01 to 2025-06-30                                                                           │
│   Instant    2025-04-14                                                                                         │
│   Duration   2025-04-14 to 2025-04-14                                                                           │
│   Duration   2025-01-01 to 2025-03-31                                                                           │
│   Instant    2025-03-07                                                                                         │
│   Instant    2024-12-31                                                                                         │
│   Duration   2022-09-08 to 2024-12-31                                                                           │
│   Duration   2024-10-01 to 2024-12-31                                                                           │
│   Instant    2024-12-05                                                                                         │
│   Duration   2024-12-05 to 2024-12-05                                                                           │
│   Instant    2024-12-04                                                                                         │
│   Instant    2024-10-21                                                                                         │
│   Duration   2024-07-01 to 2024-09-30                                                                           │
│   Instant    2024-06-30                                                                                         │
│   Duration   2023-07-01 to 2024-06-30                                                                           │
│   Duration   2024-04-01 to 2024-06-30                                                                           │
│   Duration   2023-11-01 to 2024-06-30                                                                           │
│   Duration   2024-01-01 to 2024-03-31                                                                           │
│   Instant    2024-02-12                                                                                         │
│   Duration   2024-02-12 to 2024-02-12                                                                           │
│   Duration   2023-10-01 to 2023-12-31                                                                           │
│   Duration   2023-07-01 to 2023-09-30                                                                           │
│   Instant    2023-09-12                                                                                         │
│   Instant    2023-06-30                                                                                         │
│   Instant    2022-09-08                                                                                         │
│   Instant    2016-04-11                                                                                         │
│   Duration   2016-04-11 to 2016-04-11                                                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>

In [15]:
print(cash_flow)

                                                   Consolidated Statement of Cash Flows
                                                          Multiple Periods Ended
                                             (In thousands, except shares and per share data)

                                                                                                             Jun 30, 2025   Jun 30, 2025
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  CONSOLIDATED STATEMENTS OF CASH FLOWS
    Cash flows from operating activities:
      Profit or Loss                                                                                               $1,473
      Adjustments to reconcile net income (loss) to net cash provided by operating activities:
        Depletion, depreciation, and accretion                                                                    $21,993
        Stock-based compensation                                                                                   $2,482
        Settlement of asset retirement obligations                                                                 $(385)
        Deferred income taxes                                                                                      $(468)
        Unrealized (gain) loss on derivative contracts                                                               $492
        Accrued settlements on derivative contracts                                                                $(251)
        Other                                                                                                        $(8)
      Changes in operating assets and liabilities:
        Receivables from crude oil, natural gas, and natural gas liquids revenues                                     $75
        Prepaid expenses and other current assets                                                                  $2,925
        Accounts payable and accrued liabilities and other                                                         $4,798
        State and federal taxes payable                                                                             $(74)
      Net Cash from Operating Activities                                                                          $33,052
    Cash flows from investing activities:
      Acquisition of oil and natural gas properties                                                              $(9,019)
      Capital expenditures for oil and natural gas properties                                                   $(12,623)
      Net Cash from Investing Activities                                                                        $(21,642)
    Cash flows from financing activities:
      Common stock dividends paid                                                                               $(16,347)     $(134,800)
      Common stock repurchases, including stock surrendered for tax withholding                                    $(442)
      Borrowings under senior secured credit facility                                                              $2,000
      Repayments of senior secured credit facility                                                               $(4,000)
      Debt issuance costs                                                                                           $(90)
      Proceeds from Issuance of Common Stock                                                                       $3,840
      Offering costs                                                                                               $(310)
      Net Cash from Financing Activities                                                                        $(15,349)
    Net Change in Cash                                                                                           $(3,939)
    Cash and cash equivalents, end of period
    Cash and cash equivalents, end of period
    Supplemental disclosures of cash flow information:
      Cash paid for interest on senior secured credit facility                                                     $3,082
      Income Tax Expense                                                                                             $874
      Cash refunded from income taxes                                                                              $1,000
      Non-cash investing and financing transactions:
        Increase (decrease) in accrued capital expenditures for oil and natural gas properties                      $(79)
        Oil and natural gas property costs attributable to the recognition of asset retirement obligations           $800
        Accrued debt issuance costs                                                                                  $275
        Accrued offering costs                                                                                        $10

                                                       Fiscal FY • Source: SEC XBRL

## Load 10-Q filings

In [31]:
ten_q_filings = get_filings(form='10-Q') # Get company filings by form
ten_q_filing = ten_q_filings[0] # Access to the filing no. 1
ten_q_report = ten_q_filing.obj() # Get and parse filing data object

## Get 10-Q financial finings

In [33]:
ten_q_financial_data = ten_q_report.financials # Get the company's financials
ten_q_financial_data

╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│                 Entity Information                                                                              │
│                                                                                                                 │
│   Property                   Value                                                                              │
│  ────────────────────────────────────────────────                                                               │
│   entity_name                GENERAL MILLS, INC.                                                                │
│   ticker                     GIS 34                                                                             │
│   identifier                 40704                                                                              │
│   document_type              10-Q                                                                               │
│   reporting_end_date         2025-09-17                                                                         │
│   document_period_end_date   2025-08-24                                                                         │
│   fiscal_year                2026                                                                               │
│   fiscal_period              Q1                                                                                 │
│   fiscal_year_end_month      5                                                                                  │
│   fiscal_year_end_day        31                                                                                 │
│   annual_report              False                                                                              │
│   quarterly_report           True                                                                               │
│   amendment                  False                                                                              │
│                                                                                                                 │
│                                              Financial Statements                                               │
│                                                                                                                 │
│   Type                             Definition                                                        Elements   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   BalanceSheet                     ConsolidatedBalanceSheets                                         37         │
│   BalanceSheetParenthetical        ConsolidatedBalanceSheetsParenthetical                            5          │
│   IncomeStatement                  ConsolidatedStatementsOfEarnings                                  18         │
│   CashFlowStatement                ConsolidatedStatementsOfCashFlows                                 42         │
│   StatementOfEquity                ConsolidatedStatementsOfTotalEquity                               58         │
│   StatementOfEquityParenthetical   ConsolidatedStatementsOfTotalEquityParenthetical                  5          │
│   Other                            Background                                                        2          │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCosts            2          │
│   Other                            GoodwillAndOtherIntangibleAssets                                  2          │
│   Other                            Debt                                                              2          │
│   Other                            NoncontrollingInterests                                           2          │
│   Other                            StockholdersEquity                                                2          │
│   Other                            StockPlans                                                        2          │
│   Other                            EarningsPerShare                                                  2          │
│   Other                            RetirementAndPostemploymentBenefits                               2          │
│   Other                            IncomeTaxes                                                       2          │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformation                           2          │
│   Other                            AcquisitionAndDivestitures                                        2          │
│   Other                            RiskManagementActivities                                          2          │
│   Other                            RetirementAndPostemploymentBenefitsTables                         2          │
│   Other                            AcquisitionAndDivestituresNarrativeDetails                        44         │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsNarrativ…   36         │
│   Other                            GoodwillAndOtherIntangibleAssetsTables                            5          │
│   Other                            GoodwillAndOtherIntangibleAssetsNarrativeDetails                  16         │
│   Other                            RiskManagementActivitiesTables                                    2          │
│   Other                            RiskManagementActivitiesNarrativeDetails                          51         │
│   Other                            DebtTables                                                        3          │
│   Other                            DebtNarrativeDetails                                              62         │
│   Other                            StockholdersEquityTables                                          3          │
│   Other                            StockholdersEquityNarrativeDetails                                15         │
│   Other                            StockPlansTables                                                  5          │
│   Other                            StockPlansNarrativeDetails                                        15         │
│   Other                            EarningsPerShareTables                                            3          │
│   Other                            EarningsPerShareScheduleOfBasicAndDilutedEPSAndStockOptionsAnd…   15         │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformationTables                     4          │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsTables      3          │
│   ComprehensiveIncome              ConsolidatedStatementsOfComprehensiveIncome                       15         │
│   Other                            RiskManagementActivitiesScheduleOfUnallocatedCorporateItemsDet…   6          │
│   Notes                            DebtScheduleOfComponentsOfNotesPayableDetails                     9          │
│   Other                            RetirementAndPostemploymentBenefitsComponentsOfNetPeriodicBene…   18         │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformationOperatingSegmentResults…   28         │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformationNetSalesByClassOfSimila…   15         │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsRollforw…   12         │
│   Other                            GoodwillAndOtherIntangibleAssetsComponentsOfGoodwillAndOtherIn…   10         │
│   Other                            GoodwillAndOtherIntangibleAssetsChangesInCarryingAmountOfGoodw…   20         │
│   Other                            GoodwillAndOtherIntangibleAssetsChangesInCarryingAmountOfOther…   15         │
│   Other                            StockholdersEquityScheduleOfTotalComprehensiveIncomeLossDetails   48         │
│   Other                            StockholdersEquityScheduleOfAccumulatedOtherComprehensiveIncom…   10         │
│   Other                            StockPlansScheduleOfEstimatedFairValueOfStockOptionsGrantedAnd…   7          │
│   Other                            StockPlansNetCashProceedsAndIntrinsicValueOfOptionsExercisedDe…   3          │
│   Other                            DebtScheduleOfFeePaidCommittedAndUncommittedCreditLinesDetails    16         │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsRestruct…   9          │
│   Other                            Contingencies                                                     2          │
│   CoverPage                        CoverPage                                                         53         │
│   Other                            StockPlansScheduleOfCompensationExpenseRelatedToStockBasedPaym…   9          │
│   Other                            ShareRepurchases                                                  2          │
│   Other                            ShareRepurchasesTables                                            2          │
│   Other                            ShareRepurchasesShareRepurchasesDetails                           3          │
│   Other                            StatementsOfCashFlows                                             2          │
│   Other                            StatementsOfCashFlowsTables                                       2          │
│   Other                            StatementsOfCashFlowsConsolidatedStatementsOfCashFlowsDetails     3          │
│   Other                            Inventories                                                       2          │
│   Other                            InventoriesTables                                                 2          │
│   Other                            InventoriesScheduleOfComponentsOfInventoriesDetails               6          │
│   Other                            NoncontrollingInterestsNarrativeDetails                           15         │
│   Other                            StockPlansScheduleOfGrantDateFairValueOfRestrictedStockUnitAwa…   2          │
│   Other                            InsiderTradingArrangementsDetails                                 9          │
│   Other                            AcquisitionAndDivestituresTables                                  2          │
│   Other                            InventoriesNarrativeDetails                                       2          │
│   Other                            RetirementAndPostemploymentBenefitsNarrativeDetails               2          │
│   Other                            ShareRepurchasesNarrativeDetails                                  26         │
│                                                                                                                 │
│      Facts Summary                                                                                              │
│                                                                                                                 │
│   Category      Count                                                                                           │
│  ─────────────────────                                                                                          │
│   Total Facts   730                                                                                             │
│   Contexts      158                                                                                             │
│   Units         5                                                                                               │
│   Elements      679                                                                                             │
│                                                                                                                 │
│            Reporting Periods                                                                                    │
│                                                                                                                 │
│   Type       Period                                                                                             │
│  ─────────────────────────────────────                                                                          │
│   Instant    2025-09-17                                                                                         │
│   Duration   2025-09-17 to 2025-09-17                                                                           │
│   Instant    2025-09-10                                                                                         │
│   Instant    2025-08-24                                                                                         │
│   Duration   2025-05-26 to 2025-08-24                                                                           │
│   Duration   2025-07-01 to 2025-07-01                                                                           │
│   Instant    2025-05-25                                                                                         │
│   Duration   2025-02-24 to 2025-05-25                                                                           │
│   Instant    2025-02-23                                                                                         │
│   Duration   2024-11-25 to 2025-02-23                                                                           │
│   Instant    2024-11-24                                                                                         │
│   Duration   2024-08-26 to 2024-11-24                                                                           │
│   Instant    2024-08-25                                                                                         │
│   Duration   2024-05-27 to 2024-08-25                                                                           │
│   Duration   2024-06-01 to 2024-06-01                                                                           │
│   Instant    2024-05-26                                                                                         │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

## Explore Financial Data

In [36]:
# Access the income statement
ten_q_income_statement = ten_q_financial_data.income_statement

# Access the balance sheet
ten_q_balance_sheet = ten_q_financial_data.balance_sheet

# Access the statement of cash flows
ten_q_cash_flow = ten_q_financial_data.cashflow_statement()

In [38]:
print(ten_q_income_statement)

<bound method Financials.income_statement of ╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│                 Entity Information                                                                              │
│                                                                                                                 │
│   Property                   Value                                                                              │
│  ────────────────────────────────────────────────                                                               │
│   entity_name                GENERAL MILLS, INC.                                                                │
│   ticker                     GIS 34                                                                             │
│   identifier                 40704                                                                              │
│   document_type              10-Q                                                                               │
│   reporting_end_date         2025-09-17                                                                         │
│   document_period_end_date   2025-08-24                                                                         │
│   fiscal_year                2026                                                                               │
│   fiscal_period              Q1                                                                                 │
│   fiscal_year_end_month      5                                                                                  │
│   fiscal_year_end_day        31                                                                                 │
│   annual_report              False                                                                              │
│   quarterly_report           True                                                                               │
│   amendment                  False                                                                              │
│                                                                                                                 │
│                                              Financial Statements                                               │
│                                                                                                                 │
│   Type                             Definition                                                        Elements   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   BalanceSheet                     ConsolidatedBalanceSheets                                         37         │
│   BalanceSheetParenthetical        ConsolidatedBalanceSheetsParenthetical                            5          │
│   IncomeStatement                  ConsolidatedStatementsOfEarnings                                  18         │
│   CashFlowStatement                ConsolidatedStatementsOfCashFlows                                 42         │
│   StatementOfEquity                ConsolidatedStatementsOfTotalEquity                               58         │
│   StatementOfEquityParenthetical   ConsolidatedStatementsOfTotalEquityParenthetical                  5          │
│   Other                            Background                                                        2          │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCosts            2          │
│   Other                            GoodwillAndOtherIntangibleAssets                                  2          │
│   Other                            Debt                                                              2          │
│   Other                            NoncontrollingInterests                                           2          │
│   Other                            StockholdersEquity                                                2          │
│   Other                            StockPlans                                                        2          │
│   Other                            EarningsPerShare                                                  2          │
│   Other                            RetirementAndPostemploymentBenefits                               2          │
│   Other                            IncomeTaxes                                                       2          │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformation                           2          │
│   Other                            AcquisitionAndDivestitures                                        2          │
│   Other                            RiskManagementActivities                                          2          │
│   Other                            RetirementAndPostemploymentBenefitsTables                         2          │
│   Other                            AcquisitionAndDivestituresNarrativeDetails                        44         │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsNarrativ…   36         │
│   Other                            GoodwillAndOtherIntangibleAssetsTables                            5          │
│   Other                            GoodwillAndOtherIntangibleAssetsNarrativeDetails                  16         │
│   Other                            RiskManagementActivitiesTables                                    2          │
│   Other                            RiskManagementActivitiesNarrativeDetails                          51         │
│   Other                            DebtTables                                                        3          │
│   Other                            DebtNarrativeDetails                                              62         │
│   Other                            StockholdersEquityTables                                          3          │
│   Other                            StockholdersEquityNarrativeDetails                                15         │
│   Other                            StockPlansTables                                                  5          │
│   Other                            StockPlansNarrativeDetails                                        15         │
│   Other                            EarningsPerShareTables                                            3          │
│   Other                            EarningsPerShareScheduleOfBasicAndDilutedEPSAndStockOptionsAnd…   15         │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformationTables                     4          │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsTables      3          │
│   ComprehensiveIncome              ConsolidatedStatementsOfComprehensiveIncome                       15         │
│   Other                            RiskManagementActivitiesScheduleOfUnallocatedCorporateItemsDet…   6          │
│   Notes                            DebtScheduleOfComponentsOfNotesPayableDetails                     9          │
│   Other                            RetirementAndPostemploymentBenefitsComponentsOfNetPeriodicBene…   18         │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformationOperatingSegmentResults…   28         │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformationNetSalesByClassOfSimila…   15         │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsRollforw…   12         │
│   Other                            GoodwillAndOtherIntangibleAssetsComponentsOfGoodwillAndOtherIn…   10         │
│   Other                            GoodwillAndOtherIntangibleAssetsChangesInCarryingAmountOfGoodw…   20         │
│   Other                            GoodwillAndOtherIntangibleAssetsChangesInCarryingAmountOfOther…   15         │
│   Other                            StockholdersEquityScheduleOfTotalComprehensiveIncomeLossDetails   48         │
│   Other                            StockholdersEquityScheduleOfAccumulatedOtherComprehensiveIncom…   10         │
│   Other                            StockPlansScheduleOfEstimatedFairValueOfStockOptionsGrantedAnd…   7          │
│   Other                            StockPlansNetCashProceedsAndIntrinsicValueOfOptionsExercisedDe…   3          │
│   Other                            DebtScheduleOfFeePaidCommittedAndUncommittedCreditLinesDetails    16         │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsRestruct…   9          │
│   Other                            Contingencies                                                     2          │
│   CoverPage                        CoverPage                                                         53         │
│   Other                            StockPlansScheduleOfCompensationExpenseRelatedToStockBasedPaym…   9          │
│   Other                            ShareRepurchases                                                  2          │
│   Other                            ShareRepurchasesTables                                            2          │
│   Other                            ShareRepurchasesShareRepurchasesDetails                           3          │
│   Other                            StatementsOfCashFlows                                             2          │
│   Other                            StatementsOfCashFlowsTables                                       2          │
│   Other                            StatementsOfCashFlowsConsolidatedStatementsOfCashFlowsDetails     3          │
│   Other                            Inventories                                                       2          │
│   Other                            InventoriesTables                                                 2          │
│   Other                            InventoriesScheduleOfComponentsOfInventoriesDetails               6          │
│   Other                            NoncontrollingInterestsNarrativeDetails                           15         │
│   Other                            StockPlansScheduleOfGrantDateFairValueOfRestrictedStockUnitAwa…   2          │
│   Other                            InsiderTradingArrangementsDetails                                 9          │
│   Other                            AcquisitionAndDivestituresTables                                  2          │
│   Other                            InventoriesNarrativeDetails                                       2          │
│   Other                            RetirementAndPostemploymentBenefitsNarrativeDetails               2          │
│   Other                            ShareRepurchasesNarrativeDetails                                  26         │
│                                                                                                                 │
│      Facts Summary                                                                                              │
│                                                                                                                 │
│   Category      Count                                                                                           │
│  ─────────────────────                                                                                          │
│   Total Facts   730                                                                                             │
│   Contexts      158                                                                                             │
│   Units         5                                                                                               │
│   Elements      679                                                                                             │
│                                                                                                                 │
│            Reporting Periods                                                                                    │
│                                                                                                                 │
│   Type       Period                                                                                             │
│  ─────────────────────────────────────                                                                          │
│   Instant    2025-09-17                                                                                         │
│   Duration   2025-09-17 to 2025-09-17                                                                           │
│   Instant    2025-09-10                                                                                         │
│   Instant    2025-08-24                                                                                         │
│   Duration   2025-05-26 to 2025-08-24                                                                           │
│   Duration   2025-07-01 to 2025-07-01                                                                           │
│   Instant    2025-05-25                                                                                         │
│   Duration   2025-02-24 to 2025-05-25                                                                           │
│   Instant    2025-02-23                                                                                         │
│   Duration   2024-11-25 to 2025-02-23                                                                           │
│   Instant    2024-11-24                                                                                         │
│   Duration   2024-08-26 to 2024-11-24                                                                           │
│   Instant    2024-08-25                                                                                         │
│   Duration   2024-05-27 to 2024-08-25                                                                           │
│   Duration   2024-06-01 to 2024-06-01                                                                           │
│   Instant    2024-05-26                                                                                         │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>

In [39]:
print(ten_q_balance_sheet)

<bound method Financials.balance_sheet of ╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│                 Entity Information                                                                              │
│                                                                                                                 │
│   Property                   Value                                                                              │
│  ────────────────────────────────────────────────                                                               │
│   entity_name                GENERAL MILLS, INC.                                                                │
│   ticker                     GIS 34                                                                             │
│   identifier                 40704                                                                              │
│   document_type              10-Q                                                                               │
│   reporting_end_date         2025-09-17                                                                         │
│   document_period_end_date   2025-08-24                                                                         │
│   fiscal_year                2026                                                                               │
│   fiscal_period              Q1                                                                                 │
│   fiscal_year_end_month      5                                                                                  │
│   fiscal_year_end_day        31                                                                                 │
│   annual_report              False                                                                              │
│   quarterly_report           True                                                                               │
│   amendment                  False                                                                              │
│                                                                                                                 │
│                                              Financial Statements                                               │
│                                                                                                                 │
│   Type                             Definition                                                        Elements   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   BalanceSheet                     ConsolidatedBalanceSheets                                         37         │
│   BalanceSheetParenthetical        ConsolidatedBalanceSheetsParenthetical                            5          │
│   IncomeStatement                  ConsolidatedStatementsOfEarnings                                  18         │
│   CashFlowStatement                ConsolidatedStatementsOfCashFlows                                 42         │
│   StatementOfEquity                ConsolidatedStatementsOfTotalEquity                               58         │
│   StatementOfEquityParenthetical   ConsolidatedStatementsOfTotalEquityParenthetical                  5          │
│   Other                            Background                                                        2          │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCosts            2          │
│   Other                            GoodwillAndOtherIntangibleAssets                                  2          │
│   Other                            Debt                                                              2          │
│   Other                            NoncontrollingInterests                                           2          │
│   Other                            StockholdersEquity                                                2          │
│   Other                            StockPlans                                                        2          │
│   Other                            EarningsPerShare                                                  2          │
│   Other                            RetirementAndPostemploymentBenefits                               2          │
│   Other                            IncomeTaxes                                                       2          │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformation                           2          │
│   Other                            AcquisitionAndDivestitures                                        2          │
│   Other                            RiskManagementActivities                                          2          │
│   Other                            RetirementAndPostemploymentBenefitsTables                         2          │
│   Other                            AcquisitionAndDivestituresNarrativeDetails                        44         │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsNarrativ…   36         │
│   Other                            GoodwillAndOtherIntangibleAssetsTables                            5          │
│   Other                            GoodwillAndOtherIntangibleAssetsNarrativeDetails                  16         │
│   Other                            RiskManagementActivitiesTables                                    2          │
│   Other                            RiskManagementActivitiesNarrativeDetails                          51         │
│   Other                            DebtTables                                                        3          │
│   Other                            DebtNarrativeDetails                                              62         │
│   Other                            StockholdersEquityTables                                          3          │
│   Other                            StockholdersEquityNarrativeDetails                                15         │
│   Other                            StockPlansTables                                                  5          │
│   Other                            StockPlansNarrativeDetails                                        15         │
│   Other                            EarningsPerShareTables                                            3          │
│   Other                            EarningsPerShareScheduleOfBasicAndDilutedEPSAndStockOptionsAnd…   15         │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformationTables                     4          │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsTables      3          │
│   ComprehensiveIncome              ConsolidatedStatementsOfComprehensiveIncome                       15         │
│   Other                            RiskManagementActivitiesScheduleOfUnallocatedCorporateItemsDet…   6          │
│   Notes                            DebtScheduleOfComponentsOfNotesPayableDetails                     9          │
│   Other                            RetirementAndPostemploymentBenefitsComponentsOfNetPeriodicBene…   18         │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformationOperatingSegmentResults…   28         │
│   SegmentDisclosure                BusinessSegmentAndGeographicInformationNetSalesByClassOfSimila…   15         │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsRollforw…   12         │
│   Other                            GoodwillAndOtherIntangibleAssetsComponentsOfGoodwillAndOtherIn…   10         │
│   Other                            GoodwillAndOtherIntangibleAssetsChangesInCarryingAmountOfGoodw…   20         │
│   Other                            GoodwillAndOtherIntangibleAssetsChangesInCarryingAmountOfOther…   15         │
│   Other                            StockholdersEquityScheduleOfTotalComprehensiveIncomeLossDetails   48         │
│   Other                            StockholdersEquityScheduleOfAccumulatedOtherComprehensiveIncom…   10         │
│   Other                            StockPlansScheduleOfEstimatedFairValueOfStockOptionsGrantedAnd…   7          │
│   Other                            StockPlansNetCashProceedsAndIntrinsicValueOfOptionsExercisedDe…   3          │
│   Other                            DebtScheduleOfFeePaidCommittedAndUncommittedCreditLinesDetails    16         │
│   Other                            RestructuringTransformationImpairmentAndOtherExitCostsRestruct…   9          │
│   Other                            Contingencies                                                     2          │
│   CoverPage                        CoverPage                                                         53         │
│   Other                            StockPlansScheduleOfCompensationExpenseRelatedToStockBasedPaym…   9          │
│   Other                            ShareRepurchases                                                  2          │
│   Other                            ShareRepurchasesTables                                            2          │
│   Other                            ShareRepurchasesShareRepurchasesDetails                           3          │
│   Other                            StatementsOfCashFlows                                             2          │
│   Other                            StatementsOfCashFlowsTables                                       2          │
│   Other                            StatementsOfCashFlowsConsolidatedStatementsOfCashFlowsDetails     3          │
│   Other                            Inventories                                                       2          │
│   Other                            InventoriesTables                                                 2          │
│   Other                            InventoriesScheduleOfComponentsOfInventoriesDetails               6          │
│   Other                            NoncontrollingInterestsNarrativeDetails                           15         │
│   Other                            StockPlansScheduleOfGrantDateFairValueOfRestrictedStockUnitAwa…   2          │
│   Other                            InsiderTradingArrangementsDetails                                 9          │
│   Other                            AcquisitionAndDivestituresTables                                  2          │
│   Other                            InventoriesNarrativeDetails                                       2          │
│   Other                            RetirementAndPostemploymentBenefitsNarrativeDetails               2          │
│   Other                            ShareRepurchasesNarrativeDetails                                  26         │
│                                                                                                                 │
│      Facts Summary                                                                                              │
│                                                                                                                 │
│   Category      Count                                                                                           │
│  ─────────────────────                                                                                          │
│   Total Facts   730                                                                                             │
│   Contexts      158                                                                                             │
│   Units         5                                                                                               │
│   Elements      679                                                                                             │
│                                                                                                                 │
│            Reporting Periods                                                                                    │
│                                                                                                                 │
│   Type       Period                                                                                             │
│  ─────────────────────────────────────                                                                          │
│   Instant    2025-09-17                                                                                         │
│   Duration   2025-09-17 to 2025-09-17                                                                           │
│   Instant    2025-09-10                                                                                         │
│   Instant    2025-08-24                                                                                         │
│   Duration   2025-05-26 to 2025-08-24                                                                           │
│   Duration   2025-07-01 to 2025-07-01                                                                           │
│   Instant    2025-05-25                                                                                         │
│   Duration   2025-02-24 to 2025-05-25                                                                           │
│   Instant    2025-02-23                                                                                         │
│   Duration   2024-11-25 to 2025-02-23                                                                           │
│   Instant    2024-11-24                                                                                         │
│   Duration   2024-08-26 to 2024-11-24                                                                           │
│   Instant    2024-08-25                                                                                         │
│   Duration   2024-05-27 to 2024-08-25                                                                           │
│   Duration   2024-06-01 to 2024-06-01                                                                           │
│   Instant    2024-05-26                                                                                         │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>

In [40]:
print(ten_q_cash_flow)

                                                         Consolidated Statement of Cash Flows
                                                                  Three Months Ended
                                                   (In thousands, except shares and per share data)

                                                                                                               Aug 24, 2025 (Q3)   Aug 25, 2024 (Q3)
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    Cash Flows - Operating Activities
      Profit or Loss                                                                                                  $1,204,000            $583,600
      Adjustments to reconcile net earnings to net cash provided by operating activities:
        Depreciation and amortization                                                                                   $138,700            $139,600
        After-tax earnings from joint ventures                                                                          $(6,800)           $(19,200)
        Dividends received                                                                                               $26,900             $23,100
        Stock-based compensation                                                                                         $15,100             $20,300
        Deferred income taxes                                                                                            $10,000             $16,200
        Pension and other postretirement benefit plan contributions                                                     $(5,200)            $(7,500)
        Pension and other postretirement benefit plan costs                                                             $(6,700)            $(3,200)
        Divestitures gain                                                                                           $(1,054,400)
        Restructuring, transformation, impairment, and other exit costs                                                 $(2,700)                $200
      Changes in current assets and liabilities                                                                          $58,800          $(107,600)
        Other, net                                                                                                       $19,300           $(21,300)
      Net Cash from Operating Activities                                                                                $397,000            $624,200
    Cash Flows - Investing Activities
      Payments for Property, Plant and Equipment                                                                      $(109,500)          $(140,300)
      Acquisition, net of cash acquired                                                                                                     $(7,700)
      Proceeds from divestitures                                                                                      $1,803,400
      Proceeds from disposal of land, buildings, and equipment                                                            $2,800                $600
      Other, net                                                                                                        $(1,900)              $(600)
      Net Cash from Investing Activities                                                                              $1,694,800          $(148,000)
    Cash Flows - Financing Activities
      Change in notes payable                                                                                         $(654,800)            $238,000
      Debt exchange participation incentive cash payment
      Net cash proceeds                                                                                                     $200              $9,400
      Purchases of common stock for treasury                                                                          $(500,000)          $(300,000)
      Payments of Dividends                                                                                           $(330,900)          $(337,800)
      Investment in redeemable interest
      Distributions to noncontrolling interest holders                                                                                      $(5,000)
      Other, net                                                                                                       $(21,700)           $(34,000)
      Net Cash from Financing Activities                                                                            $(1,507,200)          $(429,400)
    Effect of exchange rate changes on cash and cash equivalents                                                          $4,400              $3,300
    Net Change in Cash                                                                                                  $589,000             $50,100
    Cash and cash equivalents - end of period
    Cash and cash equivalents - end of period
    Cash Flows from changes in current assets and liabilities, excluding the effects of acquisitions and
  divestitures:
      Receivables                                                                                                         $(900)            $145,600
      Inventories                                                                                                       $135,200             $95,700
      Prepaid expenses and other current assets                                                                        $(36,600)           $(59,700)
      Accounts payable                                                                                                  $252,500             $76,400
      Other current liabilities                                                                                       $(409,000)          $(150,400)
      Changes in current assets and liabilities                                                                          $58,800          $(107,600)

                                                             Fiscal Q1 • Source: SEC XBRL

## Get all 10-K filings

In [56]:
# 1. Import necessary functions and modules
from edgar import Company
from datetime import date
from dateutil.relativedelta import relativedelta # This is a new import for better date handling

# 2. Define the company
apple = Company("AAPL")

# 3. Get all filings for the company first, as the date filtering is a separate step
all_filings = apple.get_filings()

# 4. Filter the filings for 10-K and the desired date range (last 10 years)
# The `filter()` method is part of the Filings object
# Note the syntax: 'YYYY-MM-DD:YYYY-MM-DD' is used for date ranges
end_date = date.today()
start_date = end_date - relativedelta(years=10) # A more robust way to get 10 years ago

ten_k_filings = all_filings.filter(
    form="10-K", 
    filing_date=f"{start_date.isoformat()}:{end_date.isoformat()}"
)

# 5. Loop through the filtered filings to get the financial data
all_ten_k_data = []

for filing in ten_k_filings:
    try:
        ten_k_report = filing.obj()
        financial_data = ten_k_report.financials

        all_ten_k_data.append({
            'filing_date': filing.filing_date,
            'income_statement': financial_data.income_statement,
            'balance_sheet': financial_data.balance_sheet,
            'cash_flow_statement': financial_data.cashflow_statement()
        })
    except Exception as e:
        print(f"An error occurred while processing {filing.form} dated {filing.filing_date}: {e}")

print(f"Successfully processed {len(all_ten_k_data)} 10-K filings.")

Successfully processed 10 10-K filings.

## Save data as csv files

In [59]:
import pandas as pd
# ... [Your existing code to get all_ten_k_data] ...

# 1. Combine all income statements into a single DataFrame
all_income_statements = pd.DataFrame()

for filing in all_ten_k_data:
    # First, call the method to get the Statement object
    statement_obj = filing['income_statement']()

    # Now, explicitly convert the Statement object to a pandas DataFrame
    df = statement_obj.to_dataframe()

    # Add the 'filing_date' column to the new DataFrame
    df['filing_date'] = filing['filing_date']

    # Concatenate the DataFrame
    all_income_statements = pd.concat([all_income_statements, df])

# 2. Save the combined DataFrame to an Excel file
all_income_statements.to_excel('all_apple_10k_income_statements.xlsx', index=False)

print("All income statements saved to all_apple_10k_income_statements.xlsx")

# Repeat for balance sheets and cash flows
# ...

All income statements saved to all_apple_10k_income_statements.xlsx

## Convert from a wide table to a long table

In [4]:
df = pd.read_csv('wide_table_dash.csv')
df

,m d y,Gross Margin %,Operating Margin %,Net Profit Margin %,Return on Equity (ROE),Current Ratio,FCF ($ Millions),Total Shareholders' Equity,Total Current Assets,Total Current Liabilities,Cash from Operating Activities,Payments for PP&E,Revenue:,Services,iPhone,Mac,iPad
0,"Sep 28, 2024",46.21,31.51,23.97,25.68,1.08,"108,807","$364,980","$152,987","$176,392","$118,254","-$9,447","$182,795","$18,063","$101,991","$24,079","$30,283"
1,"Sep 30, 2023",44.13,29.82,25.31,27.51,1.11,"99,584","$352,583","$143,566","$145,308","$110,543","-$10,959","$233,715","$19,909","$155,041","$25,471","$23,227"
2,"Sep 24, 2022",43.31,30.29,25.31,28.29,1.35,"111,443","$352,755","$135,405","$153,982","$122,151","-$10,708","$215,639","$24,348","$136,700","$22,831","$20,628"
3,"Sep 25, 2021",41.78,29.78,25.88,26.97,1.28,"92,953","$351,002","$134,836","$125,481","$104,038","-$11,085","$229,234","$29,980","$141,319","$25,850","$19,222"
4,"Sep 26, 2020",38.23,24.15,20.91,17.73,1.12,"73,365","$323,888","$143,713","$105,392","$80,674","-$7,309","$265,595","$37,190","$166,699","$25,484","$18,805"
5,"Sep 28, 2019",37.82,24.57,21.24,16.32,1.54,"58,896","$338,516","$162,819","$105,718","$69,391","-$10,495","$260,174","$46,291","$142,381","$25,740","$21,280"
6,"Sep 29, 2018",38.34,26.69,22.41,16.28,1.36,"64,121","$365,725","$131,339","$116,866","$77,434","-$13,313","$274,515","$53,768","$137,781","$28,622","$23,724"
7,"Sep 30, 2017",38.47,26.76,21.09,12.88,1.07,"51,774","$375,319","$128,645","$100,814","$64,225","-$12,451","$365,817","$68,425","$191,973","$35,190","$31,862"
8,"Sep 24, 2016",39.08,27.84,21.19,14.20,0.88,"53,497","$321,686","$106,869","$79,006","$66,231","-$12,734","$394,328","$78,129","$205,489","$40,177","$29,292"
9,"Sep 26, 2015",40.06,30.48,22.85,18.38,0.99,"70,019","$290,479","$89,378","$80,610","$81,266","-$11,247","$383,285","$85,200","$200,583","$29,357","$28,300"
10,"Sep 27, 2014",38.59,28.72,21.61,17.04,0.87,"50,142","$231,839","$68,531","$63,448","$59,713","-$9,571","$391,035","$96,169","$201,183","$29,984","$26,694"

In [8]:
df_long = df.melt(
    id_vars=["m d y"],        
    var_name="Metric",        
    value_name="Value"
)

df_long

            m d y          Metric    Value
0    Sep 28, 2024  Gross Margin %    46.21
1    Sep 30, 2023  Gross Margin %    44.13
2    Sep 24, 2022  Gross Margin %    43.31
3    Sep 25, 2021  Gross Margin %    41.78
4    Sep 26, 2020  Gross Margin %    38.23
..            ...             ...      ...
171  Sep 29, 2018            iPad  $23,724
172  Sep 30, 2017            iPad  $31,862
173  Sep 24, 2016            iPad  $29,292
174  Sep 26, 2015            iPad  $28,300
175  Sep 27, 2014            iPad  $26,694

[176 rows x 3 columns]

In [9]:
df_long.to_csv("financials_long.csv", index=False)