# Edgar Tools Tutorial

- Dev's Guide (Maybe)
- https://github.com/dgunning/edgartools?tab=readme-ov-file
- Quick User Guides
- https://edgartools.readthedocs.io/en/latest/quick-guide/

# Working with Company Data
-  This is from the GitHub tutorial page

In [1]:
# 1. Import the library
from edgar import *

# 2. Tell the SEC who you are (required by SEC regulations)
set_identity("info.pakkapols@gmail.com")

# 3. Find a company
company = Company("AAPL")  # Microsoft

# 4. Get company filings
filings = company.get_filings() 

# 5. Filter by form 
insider_filings = filings.filter(form="4")  # Insider transactions

# 6. Get the latest filing
insider_filing = insider_filings[0]

# 7. Convert to a data object
ownership = insider_filing.obj()

In [2]:
company

╭────────────────────────────────────────────── 🏢 Apple Inc. AAPL ───────────────────────────────────────────────╮
│                                                                                                                 │
│                                                                                                                 │
│ ╭───────────────────────────────────────────────── 📋 Entity ─────────────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   CIK   320193   Type   Operating   ○                                                                       │ │
│ │                                                                                                             │ │
│ │                                                                                                             │ │
│ │   Category                  Industry                     Fiscal Year End                                    │ │
│ │  ────────────────────────────────────────────────────────────────────────                                   │ │
│ │   Large accelerated filer   3571: Electronic Computers   Sep 27                                             │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ ╭─────────────────────────────────────────────── 📈 Exchanges ────────────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   Exchange   Symbol                                                                                         │ │
│ │  ───────────────────                                                                                        │ │
│ │   Nasdaq     AAPL                                                                                           │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│ ╭─── 🏢 Business Address ────╮      ╭──── 📫 Mailing Address ────╮     ╭── 📞 Contact Information ──╮           │
│ │ ONE APPLE PARK WAY         │      │ ONE APPLE PARK WAY         │     │                            │           │
│ │ CUPERTINO, CA 95014        │      │ CUPERTINO, CA 95014        │     │   Phone   (408) 996-1010   │           │
│ ╰────────────────────────────╯      ╰────────────────────────────╯     │                            │           │
│                                                                        ╰────────────────────────────╯           │
│ ╭────────────────────────────────────────────── 📜 Former Names ──────────────────────────────────────────────╮ │
│ │                                                                                                             │ │
│ │   APPLE INC                January 2007 to August 2019                                                      │ │
│ │   APPLE COMPUTER INC       January 1994 to January 2007                                                     │ │
│ │   APPLE COMPUTER INC/ FA   July 1997 to July 1997                                                           │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────── SEC Entity Data ────────────────────────────────────────────────╯

In [3]:
filings

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│                                                                              Filing                             │
│    Form        Description                                                   Date         Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    4           Statement of changes in beneficial ownership                  2025-08-29   0001214128-25-0000…   │
│    144         Notice of proposed sale                                       2025-08-28   0001921094-25-0010…   │
│    4           Statement of changes in beneficial ownership                  2025-08-27   0001631982-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-08-12   0001767094-25-0000…   │
│    144         Notice of proposed sale                                       2025-08-08   0001969223-25-0005…   │
│    10-Q        Quarterly report for public companies                         2025-08-01   0000320193-25-0000…   │
│    8-K         Current report                                                2025-07-31   0000320193-25-0000…   │
│    SCHEDULE    Beneficial ownership by passive investors/institutions        2025-07-29   0000932471-25-0007…   │
│    13G/A                                                                                                        │
│    3           Initial statement of beneficial ownership                     2025-07-25   0000320193-25-0000…   │
│    8-K         Current report                                                2025-07-25   0001140361-25-0273…   │
│    8-K         Current report                                                2025-07-09   0001140361-25-0252…   │
│    25-NSE      Notice of matured/redeemed/retired securities by exchanges    2025-05-22   0001354457-25-0004…   │
│    4           Statement of changes in beneficial ownership                  2025-05-14   0000320193-25-0000…   │
│    8-K         Current report                                                2025-05-12   0001140361-25-0184…   │
│    424B2       Primary offering prospectus                                   2025-05-06   0001140361-25-0175…   │
│    FWP         Filing of free writing prospectuses                           2025-05-06   0001140361-25-0174…   │
│    424B2       Primary offering prospectus                                   2025-05-05   0001140361-25-0172…   │
│    10-Q        Quarterly report for public companies                         2025-05-02   0000320193-25-0000…   │
│    8-K         Current report                                                2025-05-01   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-25   0000320193-25-0000…   │
│    144         Notice of proposed sale                                       2025-04-23   0001950047-25-0025…   │
│    4           Statement of changes in beneficial ownership                  2025-04-17   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-17   0000320193-25-0000…   │
│    SD          Specialized disclosure report on conflict minerals or         2025-04-04   0001140361-25-0123…   │
│                resource extraction payments                                                                     │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    144         Notice of proposed sale                                       2025-04-02   0001950047-25-0023…   │
│    144         Notice of proposed sale                                       2025-04-02   0001969223-25-0002…   │
│    144         Notice of proposed sale                                       2025-04-02   0001959173-25-0024…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    8-K         Current report                                                2025-02-25   0001140361-25-0058…   │
│    PX14A6G     Exempt solicitation                                           2025-02-13   0001096906-25-0001…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    144         Notice of proposed sale                                       2025-02-03   0001921094-25-0000…   │
│    10-Q        Quarterly report for public companies                         2025-01-31   0000320193-25-0000…   │
│    8-K         Current report                                                2025-01-30   0000320193-25-0000…   │
│                                                                                                                 │
│                                                                                                                 │
│                                                                                                                 │
│ Showing 1 to 50 of 2,164 filings. Page using ← prev() and next() →                                              │
╰─────────────────────────────── Company filings between 1994-01-26 and 2025-08-29 ───────────────────────────────╯

In [4]:
insider_filings

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│                                                                              Filing                             │
│    Form        Description                                                   Date         Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    4           Statement of changes in beneficial ownership                  2025-08-29   0001214128-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-08-27   0001631982-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-08-12   0001767094-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-05-14   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-25   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-17   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-17   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-04-03   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-27   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2025-02-04   0000320193-25-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-12-18   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-11-19   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-11-19   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-11-07   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-17   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-08   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-03   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-03   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-03   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-03   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-03   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-01   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-01   0000320193-24-0001…   │
│    4           Statement of changes in beneficial ownership                  2024-10-01   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-10-01   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-10-01   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-10-01   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-08-19   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-08-13   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-08-07   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-06-03   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-05-17   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-05-14   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-04-17   0000320193-24-0000…   │
│    4           Statement of changes in beneficial ownership                  2024-04-15   0000320193-24-0000…   │
│                                                                                                                 │
│                                                                                                                 │
│                                                                                                                 │
│ Showing 1 to 50 of 1,298 filings. Page using ← prev() and next() →                                              │
╰─────────────────────────────── Company filings between 2003-03-21 and 2025-08-29 ───────────────────────────────╯

In [5]:
insider_filing = insider_filings[0]
print(insider_filing)

Filing(company='Apple Inc.', cik=320193, form='4', filing_date='2025-08-29', accession_no='0001214128-25-000005')

In [6]:
print(ownership)

╭──────────────────────────── Ownership Transactions (Sale)  ────────────────────────────╮
│ Insider:  Arthur D Levinson                                                            │
│ Position: Director                                                                     │
│ Company:  Apple Inc. (AAPL)                                                            │
│ Date:     2025-08-28                                                                   │
│ Form:     Form 4                                                                       │
│                               Common Stock Transactions                                │
│                                                                                        │
│   Type             Code   Description         Shares   Price/Share             Value   │
│  ────────────────────────────────────────────────────────────────────────────────────  │
│   SALE              S     Open Market Sale    90,000       $232.07    $20,886,300.00   │
│   NET CHANGE                                 -90,000                 $-20,886,300.00   │
│   AVG SELL PRICE                                           $232.07                     │
│                                                                                        │
│ REMAINING POSITION: 4,069,576 shares                                                   │
╰────────────────────────────────────────────────────────────────────────────────────────╯

In [7]:
company.get_financials()

╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│            Entity Information                                                                                   │
│                                                                                                                 │
│   Property                   Value                                                                              │
│  ───────────────────────────────────────                                                                        │
│   entity_name                Apple Inc.                                                                         │
│   ticker                     AAPL                                                                               │
│   identifier                 320193                                                                             │
│   document_type              10-K                                                                               │
│   reporting_end_date         2024-10-18                                                                         │
│   document_period_end_date   2024-09-28                                                                         │
│   fiscal_year                2024                                                                               │
│   fiscal_period              FY                                                                                 │
│   fiscal_year_end_month      9                                                                                  │
│   fiscal_year_end_day        28                                                                                 │
│   annual_report              True                                                                               │
│   quarterly_report           False                                                                              │
│   amendment                  False                                                                              │
│                                                                                                                 │
│                                              Financial Statements                                               │
│                                                                                                                 │
│   Type                        Definition                                                             Elements   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   CoverPage                   CoverPage                                                              50         │
│   Other                       AuditorInformation                                                     4          │
│   IncomeStatement             CONSOLIDATEDSTATEMENTSOFOPERATIONS                                     25         │
│   ComprehensiveIncome         CONSOLIDATEDSTATEMENTSOFCOMPREHENSIVEINCOME                            14         │
│   BalanceSheet                CONSOLIDATEDBALANCESHEETS                                              38         │
│   BalanceSheetParenthetical   CONSOLIDATEDBALANCESHEETSParenthetical                                 5          │
│   StatementOfEquity           CONSOLIDATEDSTATEMENTSOFSHAREHOLDERSEQUITY                             18         │
│   CashFlowStatement           CONSOLIDATEDSTATEMENTSOFCASHFLOWS                                      35         │
│   AccountingPolicies          SummaryofSignificantAccountingPolicies                                 2          │
│   Other                       Revenue                                                                2          │
│   Other                       EarningsPerShare                                                       2          │
│   Other                       FinancialInstruments                                                   2          │
│   Other                       PropertyPlantandEquipment                                              2          │
│   Other                       ConsolidatedFinancialStatementDetails                                  2          │
│   Other                       IncomeTaxes                                                            2          │
│   Other                       Leases                                                                 3          │
│   Other                       Debt                                                                   2          │
│   Other                       ShareholdersEquity                                                     2          │
│   Other                       ShareBasedCompensation                                                 2          │
│   Other                       CommitmentsContingenciesandSupplyConcentrations                        2          │
│   SegmentDisclosure           SegmentInformationandGeographicData                                    2          │
│   AccountingPolicies          SummaryofSignificantAccountingPoliciesPolicies                         14         │
│   Other                       RevenueTables                                                          2          │
│   Other                       EarningsPerShareTables                                                 2          │
│   Other                       FinancialInstrumentsTables                                             4          │
│   Other                       PropertyPlantandEquipmentTables                                        2          │
│   Other                       ConsolidatedFinancialStatementDetailsTables                            4          │
│   Other                       IncomeTaxesTables                                                      5          │
│   Other                       LeasesTables                                                           4          │
│   Other                       DebtTables                                                             4          │
│   Other                       ShareholdersEquityTables                                               2          │
│   Other                       ShareBasedCompensationTables                                           3          │
│   Other                       CommitmentsContingenciesandSupplyConcentrationsTables                  2          │
│   SegmentDisclosure           SegmentInformationandGeographicDataTables                              4          │
│   Other                       RevenueAdditionalInformationDetails                                    3          │
│   Other                       RevenueNetSalesDisaggregatedbySignificantProductsandServicesDetails    11         │
│   Other                       RevenueDeferredRevenueExpectedTimingofRealizationDetails               6          │
│   Other                       EarningsPerShareComputationofBasicandDilutedEarningsPerShareDetails    9          │
│   Other                       EarningsPerShareAdditionalInformationDetails                           7          │
│   Other                       FinancialInstrumentsCashCashEquivalentsandMarketableSecuritiesDetai…   42         │
│   Other                       FinancialInstrumentsAdditionalInformationDetails                       30         │
│   Other                       FinancialInstrumentsNotionalAmountsAssociatedwithDerivativeInstrume…   12         │
│   Other                       FinancialInstrumentsDerivativeInstrumentsDesignatedasFairValueHedge…   5          │
│   Other                       PropertyPlantandEquipmentGrossPropertyPlantandEquipmentbyMajorAsset…   11         │
│   Other                       PropertyPlantandEquipmentAdditionalInformationDetails                  2          │
│   Other                       ConsolidatedFinancialStatementDetailsOtherNonCurrentAssetsDetails      4          │
│   Other                       ConsolidatedFinancialStatementDetailsOtherCurrentLiabilitiesDetails    4          │
│   Other                       ConsolidatedFinancialStatementDetailsOtherNonCurrentLiabilitiesDeta…   4          │
│   Other                       IncomeTaxesAdditionalInformationDetails                                28         │
│   Other                       IncomeTaxesProvisionforIncomeTaxesDetails                              14         │
│   Other                       IncomeTaxesReconciliationofProvisionforIncomeTaxestoAmountComputedb…   10         │
│   Other                       IncomeTaxesSignificantComponentsofDeferredTaxAssetsandLiabilitiesDe…   20         │
│   Other                       IncomeTaxesAggregateChangesinGrossUnrecognizedTaxBenefitsDetails       8          │
│   Other                       LeasesAdditionalInformationDetails                                     19         │
│   Other                       LeasesROUAssetsandLeaseLiabilitiesDetails                              16         │
│   Other                       LeasesLeaseLiabilityMaturitiesDetails                                  31         │
│   Other                       DebtAdditionalInformationDetails                                       13         │
│   Other                       DebtSummaryofCashFlowsAssociatedwithCommercialPaperDetails             8          │
│   Other                       DebtSummaryofTermDebtDetails                                           23         │
│   Other                       DebtFuturePrincipalPaymentsforTermDebtDetails                          8          │
│   Other                       ShareholdersEquityAdditionalInformationDetails                         4          │
│   StatementOfEquity           ShareholdersEquitySharesofCommonStockDetails                           10         │
│   Other                       ShareBasedCompensationAdditionalInformationDetails                     17         │
│   Other                       ShareBasedCompensationRestrictedStockUnitActivityandRelatedInformat…   18         │
│   Other                       ShareBasedCompensationSummaryofShareBasedCompensationExpenseandtheR…   3          │
│   Other                       CommitmentsContingenciesandSupplyConcentrationsFuturePaymentsUnderU…   9          │
│   SegmentDisclosure           SegmentInformationandGeographicDataInformationbyReportableSegmentDe…   12         │
│   SegmentDisclosure           SegmentInformationandGeographicDataReconciliationofSegmentOperating…   11         │
│   SegmentDisclosure           SegmentInformationandGeographicDataNetSalesforCountriesthatIndividu…   9          │
│   SegmentDisclosure           SegmentInformationandGeographicDataLongLivedAssetsforCountriesthatI…   9          │
│   Disclosures                 AwardTimingDisclosure                                                  21         │
│   Disclosures                 ErrCompDisclosure                                                      20         │
│   Disclosures                 PvpDisclosure                                                          54         │
│   Other                       InsiderTradingArrangements                                             20         │
│   Other                       InsiderTradingPoliciesProc                                             3          │
│                                                                                                                 │
│      Facts Summary                                                                                              │
│                                                                                                                 │
│   Category      Count                                                                                           │
│  ─────────────────────                                                                                          │
│   Total Facts   1127                                                                                            │
│   Contexts      193                                                                                             │
│   Units         7                                                                                               │
│   Elements      684                                                                                             │
│                                                                                                                 │
│            Reporting Periods                                                                                    │
│                                                                                                                 │
│   Type       Period                                                                                             │
│  ─────────────────────────────────────                                                                          │
│   Instant    2024-10-18                                                                                         │
│   Instant    2024-09-28                                                                                         │
│   Duration   2023-10-01 to 2024-09-28                                                                           │
│   Duration   2024-06-30 to 2024-09-28                                                                           │
│   Instant    2024-03-29                                                                                         │
│   Instant    2023-09-30                                                                                         │
│   Duration   2022-09-25 to 2023-09-30                                                                           │
│   Instant    2022-09-24                                                                                         │
│   Duration   2021-09-26 to 2022-09-24                                                                           │
│   Instant    2022-03-04                                                                                         │
│   Instant    2021-09-25                                                                                         │
│   Instant    2016-08-30                                                                                         │
│   Duration   2016-08-30 to 2016-08-30                                                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

# Get Latest Financial Statements

In [8]:
# Get Apple's latest financials
company = Company("AAPL")
financials = company.get_financials()

# Access individual statements
balance_sheet = financials.balance_sheet
income_statement = financials.income_statement()
cash_flow = financials.cashflow_statement()

In [9]:
print(balance_sheet)

<bound method Financials.balance_sheet of ╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│            Entity Information                                                                                   │
│                                                                                                                 │
│   Property                   Value                                                                              │
│  ───────────────────────────────────────                                                                        │
│   entity_name                Apple Inc.                                                                         │
│   ticker                     AAPL                                                                               │
│   identifier                 320193                                                                             │
│   document_type              10-K                                                                               │
│   reporting_end_date         2024-10-18                                                                         │
│   document_period_end_date   2024-09-28                                                                         │
│   fiscal_year                2024                                                                               │
│   fiscal_period              FY                                                                                 │
│   fiscal_year_end_month      9                                                                                  │
│   fiscal_year_end_day        28                                                                                 │
│   annual_report              True                                                                               │
│   quarterly_report           False                                                                              │
│   amendment                  False                                                                              │
│                                                                                                                 │
│                                              Financial Statements                                               │
│                                                                                                                 │
│   Type                        Definition                                                             Elements   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   CoverPage                   CoverPage                                                              50         │
│   Other                       AuditorInformation                                                     4          │
│   IncomeStatement             CONSOLIDATEDSTATEMENTSOFOPERATIONS                                     25         │
│   ComprehensiveIncome         CONSOLIDATEDSTATEMENTSOFCOMPREHENSIVEINCOME                            14         │
│   BalanceSheet                CONSOLIDATEDBALANCESHEETS                                              38         │
│   BalanceSheetParenthetical   CONSOLIDATEDBALANCESHEETSParenthetical                                 5          │
│   StatementOfEquity           CONSOLIDATEDSTATEMENTSOFSHAREHOLDERSEQUITY                             18         │
│   CashFlowStatement           CONSOLIDATEDSTATEMENTSOFCASHFLOWS                                      35         │
│   AccountingPolicies          SummaryofSignificantAccountingPolicies                                 2          │
│   Other                       Revenue                                                                2          │
│   Other                       EarningsPerShare                                                       2          │
│   Other                       FinancialInstruments                                                   2          │
│   Other                       PropertyPlantandEquipment                                              2          │
│   Other                       ConsolidatedFinancialStatementDetails                                  2          │
│   Other                       IncomeTaxes                                                            2          │
│   Other                       Leases                                                                 3          │
│   Other                       Debt                                                                   2          │
│   Other                       ShareholdersEquity                                                     2          │
│   Other                       ShareBasedCompensation                                                 2          │
│   Other                       CommitmentsContingenciesandSupplyConcentrations                        2          │
│   SegmentDisclosure           SegmentInformationandGeographicData                                    2          │
│   AccountingPolicies          SummaryofSignificantAccountingPoliciesPolicies                         14         │
│   Other                       RevenueTables                                                          2          │
│   Other                       EarningsPerShareTables                                                 2          │
│   Other                       FinancialInstrumentsTables                                             4          │
│   Other                       PropertyPlantandEquipmentTables                                        2          │
│   Other                       ConsolidatedFinancialStatementDetailsTables                            4          │
│   Other                       IncomeTaxesTables                                                      5          │
│   Other                       LeasesTables                                                           4          │
│   Other                       DebtTables                                                             4          │
│   Other                       ShareholdersEquityTables                                               2          │
│   Other                       ShareBasedCompensationTables                                           3          │
│   Other                       CommitmentsContingenciesandSupplyConcentrationsTables                  2          │
│   SegmentDisclosure           SegmentInformationandGeographicDataTables                              4          │
│   Other                       RevenueAdditionalInformationDetails                                    3          │
│   Other                       RevenueNetSalesDisaggregatedbySignificantProductsandServicesDetails    11         │
│   Other                       RevenueDeferredRevenueExpectedTimingofRealizationDetails               6          │
│   Other                       EarningsPerShareComputationofBasicandDilutedEarningsPerShareDetails    9          │
│   Other                       EarningsPerShareAdditionalInformationDetails                           7          │
│   Other                       FinancialInstrumentsCashCashEquivalentsandMarketableSecuritiesDetai…   42         │
│   Other                       FinancialInstrumentsAdditionalInformationDetails                       30         │
│   Other                       FinancialInstrumentsNotionalAmountsAssociatedwithDerivativeInstrume…   12         │
│   Other                       FinancialInstrumentsDerivativeInstrumentsDesignatedasFairValueHedge…   5          │
│   Other                       PropertyPlantandEquipmentGrossPropertyPlantandEquipmentbyMajorAsset…   11         │
│   Other                       PropertyPlantandEquipmentAdditionalInformationDetails                  2          │
│   Other                       ConsolidatedFinancialStatementDetailsOtherNonCurrentAssetsDetails      4          │
│   Other                       ConsolidatedFinancialStatementDetailsOtherCurrentLiabilitiesDetails    4          │
│   Other                       ConsolidatedFinancialStatementDetailsOtherNonCurrentLiabilitiesDeta…   4          │
│   Other                       IncomeTaxesAdditionalInformationDetails                                28         │
│   Other                       IncomeTaxesProvisionforIncomeTaxesDetails                              14         │
│   Other                       IncomeTaxesReconciliationofProvisionforIncomeTaxestoAmountComputedb…   10         │
│   Other                       IncomeTaxesSignificantComponentsofDeferredTaxAssetsandLiabilitiesDe…   20         │
│   Other                       IncomeTaxesAggregateChangesinGrossUnrecognizedTaxBenefitsDetails       8          │
│   Other                       LeasesAdditionalInformationDetails                                     19         │
│   Other                       LeasesROUAssetsandLeaseLiabilitiesDetails                              16         │
│   Other                       LeasesLeaseLiabilityMaturitiesDetails                                  31         │
│   Other                       DebtAdditionalInformationDetails                                       13         │
│   Other                       DebtSummaryofCashFlowsAssociatedwithCommercialPaperDetails             8          │
│   Other                       DebtSummaryofTermDebtDetails                                           23         │
│   Other                       DebtFuturePrincipalPaymentsforTermDebtDetails                          8          │
│   Other                       ShareholdersEquityAdditionalInformationDetails                         4          │
│   StatementOfEquity           ShareholdersEquitySharesofCommonStockDetails                           10         │
│   Other                       ShareBasedCompensationAdditionalInformationDetails                     17         │
│   Other                       ShareBasedCompensationRestrictedStockUnitActivityandRelatedInformat…   18         │
│   Other                       ShareBasedCompensationSummaryofShareBasedCompensationExpenseandtheR…   3          │
│   Other                       CommitmentsContingenciesandSupplyConcentrationsFuturePaymentsUnderU…   9          │
│   SegmentDisclosure           SegmentInformationandGeographicDataInformationbyReportableSegmentDe…   12         │
│   SegmentDisclosure           SegmentInformationandGeographicDataReconciliationofSegmentOperating…   11         │
│   SegmentDisclosure           SegmentInformationandGeographicDataNetSalesforCountriesthatIndividu…   9          │
│   SegmentDisclosure           SegmentInformationandGeographicDataLongLivedAssetsforCountriesthatI…   9          │
│   Disclosures                 AwardTimingDisclosure                                                  21         │
│   Disclosures                 ErrCompDisclosure                                                      20         │
│   Disclosures                 PvpDisclosure                                                          54         │
│   Other                       InsiderTradingArrangements                                             20         │
│   Other                       InsiderTradingPoliciesProc                                             3          │
│                                                                                                                 │
│      Facts Summary                                                                                              │
│                                                                                                                 │
│   Category      Count                                                                                           │
│  ─────────────────────                                                                                          │
│   Total Facts   1127                                                                                            │
│   Contexts      193                                                                                             │
│   Units         7                                                                                               │
│   Elements      684                                                                                             │
│                                                                                                                 │
│            Reporting Periods                                                                                    │
│                                                                                                                 │
│   Type       Period                                                                                             │
│  ─────────────────────────────────────                                                                          │
│   Instant    2024-10-18                                                                                         │
│   Instant    2024-09-28                                                                                         │
│   Duration   2023-10-01 to 2024-09-28                                                                           │
│   Duration   2024-06-30 to 2024-09-28                                                                           │
│   Instant    2024-03-29                                                                                         │
│   Instant    2023-09-30                                                                                         │
│   Duration   2022-09-25 to 2023-09-30                                                                           │
│   Instant    2022-09-24                                                                                         │
│   Duration   2021-09-26 to 2022-09-24                                                                           │
│   Instant    2022-03-04                                                                                         │
│   Instant    2021-09-25                                                                                         │
│   Instant    2016-08-30                                                                                         │
│   Duration   2016-08-30 to 2016-08-30                                                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
>

In [10]:
print(income_statement)

                                  Consolidated Statement of Income
                                             Year Ended
                    (In millions, except shares in thousands and per share data)

                                                        Sep 28, 2024   Sep 30, 2023   Sep 24, 2022
 ──────────────────────────────────────────────────────────────────────────────────────────────────
          Products
          Services
        Contract Revenue:                                   $391,035       $383,285       $394,328
          Products                                          $294,866       $298,085       $316,199
          Services                                           $96,169        $85,200        $78,129
          iPhone                                            $201,183       $200,583       $205,489
          Mac                                                $29,984        $29,357        $40,177
          iPad                                               $26,694        $28,300        $29,292
          Wearables, Home and Accessories                    $37,005        $39,845        $41,241
          Americas                                          $167,045       $162,560       $169,658
          Europe                                            $101,328        $94,294        $95,118
          Japan                                              $25,052        $24,257        $25,977
          Rest of Asia Pacific                               $30,658        $29,615        $29,375
          U.S.                                              $142,196       $138,573       $147,859
          China                                              $66,952        $72,559        $74,200
          Other countries                                   $181,887       $172,153       $172,269
        Cost of Goods and Services Sold:                  $(210,352)     $(214,137)     $(223,546)
          Products                                        $(185,233)     $(189,282)     $(201,471)
          Services                                         $(25,119)      $(24,855)      $(22,075)
        Gross Profit                                        $180,683       $169,148       $170,782
        Operating expenses:
          Research and Development Expense:                  $31,370        $29,915        $26,251
            Segment reconciling items                        $31,370        $29,915        $26,251
          Selling, General and Administrative Expense        $26,097        $24,932        $25,094
          Operating Expenses                                 $57,467        $54,847        $51,345
        Operating Income:                                   $123,216       $114,301       $119,437
          Americas                                           $67,656        $60,508        $62,683
          Europe                                             $41,790        $36,098        $35,233
          Greater China                                      $27,082        $30,328        $31,153
          Japan                                              $12,454        $11,888        $12,257
          Rest of Asia Pacific                               $13,062        $12,066        $11,569
          Operating segments                                $162,044       $150,888       $152,895
        Nonoperating Income/Expense                             $269         $(565)         $(334)
        Income Before Tax from Continuing Operations         123,485        113,736        119,103
        Income Tax Expense                                   $29,749        $16,741        $19,300
        Net Income:                                          $93,736        $96,995        $99,803
          Retained earnings/(Accumulated deficit)            $93,736        $96,995        $99,803
        Earnings Per Share
          Earnings Per Share (Basic)                            6.11           6.16           6.15
          Earnings Per Share (Diluted)                          6.08           6.13           6.11
        Shares Outstanding
          Shares Outstanding (Basic)                      15,343,783     15,744,231     16,215,963
          Shares Outstanding (Diluted)                    15,408,095     15,812,547     16,325,819

                                    Fiscal FY • Source: SEC XBRL

In [11]:
print(cash_flow)

                                                Consolidated Statement of Cash Flows
                                                             Year Ended
                                          (In millions, except shares and per share data)

                                                                                        Sep 28, 2024   Sep 30, 2023   Sep 24, 2022
 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    Cash, cash equivalents, and restricted cash and cash equivalents, ending balances
    Operating activities:
      Net Income                                                                             $93,736        $96,995        $99,803
      Adjustments to reconcile net income to cash generated by operating activities:
        Depreciation and amortization                                                        $11,445        $11,519        $11,104
        Share-based compensation expense                                                     $11,688        $10,833         $9,038
        Other                                                                               $(2,266)       $(2,227)         $1,006
        Changes in operating assets and liabilities:
          Accounts receivable, net                                                          $(3,788)       $(1,688)       $(1,823)
          Vendor non-trade receivables                                                      $(1,356)         $1,271       $(7,520)
          Inventories                                                                       $(1,046)       $(1,618)         $1,484
          Other current and non-current assets                                             $(11,731)       $(5,684)       $(6,499)
          Accounts payable                                                                    $6,020       $(1,889)         $9,448
          Other current and non-current liabilities                                          $15,552         $3,031         $6,110
      Net Cash from Operating Activities                                                    $118,254       $110,543       $122,151
    Investing activities:
      Purchases of marketable securities                                                   $(48,656)      $(29,513)      $(76,923)
      Proceeds from Maturities, Prepayments and Calls of Securities                          $51,211        $39,686        $29,917
      Proceeds from Sale of Debt Securities,                                                 $11,135         $5,828        $37,446
      Payments for Property, Plant and Equipment                                            $(9,447)      $(10,959)      $(10,708)
      Other                                                                                 $(1,308)       $(1,337)       $(2,086)
      Net Cash from Investing Activities                                                      $2,935         $3,705      $(22,354)
    Financing activities:
      Tax Withholding for Share-Based Compensation                                          $(5,441)       $(5,431)       $(6,223)
      Payments of Dividends                                                                $(15,234)      $(15,025)      $(14,841)
      Repurchases of common stock                                                          $(94,949)      $(77,550)      $(89,402)
      Proceeds from Issuance of Long-Term Debt                                                               $5,228         $5,465
      Repayments of term debt                                                               $(9,958)      $(11,151)       $(9,543)
      Proceeds from (Repayments of) Commercial Paper                                          $3,960       $(3,978)         $3,955
      Other                                                                                   $(361)         $(581)         $(160)
      Net Cash from Financing Activities                                                  $(121,983)     $(108,488)     $(110,749)
    Net Change in Cash                                                                        $(794)         $5,760      $(10,952)
    Cash, cash equivalents, and restricted cash and cash equivalents, ending balances
    Supplemental cash flow disclosure:
      Income Tax Expense                                                                     $26,102        $18,679        $19,573

                                                    Fiscal FY • Source: SEC XBRL

# Download 10-Q reports (Getting Filings)

In [12]:
filings = company.get_filings(form="10-Q")
filings

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│                                                                              Filing                             │
│    Form        Description                                                   Date         Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    10-Q        Quarterly report for public companies                         2025-08-01   0000320193-25-0000…   │
│    10-Q        Quarterly report for public companies                         2025-05-02   0000320193-25-0000…   │
│    10-Q        Quarterly report for public companies                         2025-01-31   0000320193-25-0000…   │
│    10-Q        Quarterly report for public companies                         2024-08-02   0000320193-24-0000…   │
│    10-Q        Quarterly report for public companies                         2024-05-03   0000320193-24-0000…   │
│    10-Q        Quarterly report for public companies                         2024-02-02   0000320193-24-0000…   │
│    10-Q        Quarterly report for public companies                         2023-08-04   0000320193-23-0000…   │
│    10-Q        Quarterly report for public companies                         2023-05-05   0000320193-23-0000…   │
│    10-Q        Quarterly report for public companies                         2023-02-03   0000320193-23-0000…   │
│    10-Q        Quarterly report for public companies                         2022-07-29   0000320193-22-0000…   │
│    10-Q        Quarterly report for public companies                         2022-04-29   0000320193-22-0000…   │
│    10-Q        Quarterly report for public companies                         2022-01-28   0000320193-22-0000…   │
│    10-Q        Quarterly report for public companies                         2021-07-28   0000320193-21-0000…   │
│    10-Q        Quarterly report for public companies                         2021-04-29   0000320193-21-0000…   │
│    10-Q        Quarterly report for public companies                         2021-01-28   0000320193-21-0000…   │
│    10-Q        Quarterly report for public companies                         2020-07-31   0000320193-20-0000…   │
│    10-Q        Quarterly report for public companies                         2020-05-01   0000320193-20-0000…   │
│    10-Q        Quarterly report for public companies                         2020-01-29   0000320193-20-0000…   │
│    10-Q        Quarterly report for public companies                         2019-07-31   0000320193-19-0000…   │
│    10-Q        Quarterly report for public companies                         2019-05-01   0000320193-19-0000…   │
│    10-Q        Quarterly report for public companies                         2019-01-30   0000320193-19-0000…   │
│    10-Q        Quarterly report for public companies                         2018-08-01   0000320193-18-0001…   │
│    10-Q        Quarterly report for public companies                         2018-05-02   0000320193-18-0000…   │
│    10-Q        Quarterly report for public companies                         2018-02-02   0000320193-18-0000…   │
│    10-Q        Quarterly report for public companies                         2017-08-02   0000320193-17-0000…   │
│    10-Q        Quarterly report for public companies                         2017-05-03   0001628280-17-0047…   │
│    10-Q        Quarterly report for public companies                         2017-02-01   0001628280-17-0007…   │
│    10-Q        Quarterly report for public companies                         2016-07-27   0001628280-16-0178…   │
│    10-Q        Quarterly report for public companies                         2016-04-27   0001193125-16-5596…   │
│    10-Q        Quarterly report for public companies                         2016-01-27   0001193125-16-4398…   │
│    10-Q        Quarterly report for public companies                         2015-07-22   0001193125-15-2599…   │
│    10-Q        Quarterly report for public companies                         2015-04-28   0001193125-15-1531…   │
│    10-Q        Quarterly report for public companies                         2015-01-28   0001193125-15-0236…   │
│    10-Q        Quarterly report for public companies                         2014-07-23   0001193125-14-2771…   │
│    10-Q        Quarterly report for public companies                         2014-04-24   0001193125-14-1573…   │
│    10-Q        Quarterly report for public companies                         2014-01-28   0001193125-14-0244…   │
│    10-Q        Quarterly report for public companies                         2013-07-24   0001193125-13-3006…   │
│    10-Q        Quarterly report for public companies                         2013-04-24   0001193125-13-1682…   │
│    10-Q        Quarterly report for public companies                         2013-01-24   0001193125-13-0223…   │
│    10-Q        Quarterly report for public companies                         2012-07-25   0001193125-12-3145…   │
│    10-Q        Quarterly report for public companies                         2012-04-25   0001193125-12-1823…   │
│    10-Q        Quarterly report for public companies                         2012-01-25   0001193125-12-0233…   │
│    10-Q        Quarterly report for public companies                         2011-07-20   0001193125-11-1924…   │
│    10-Q        Quarterly report for public companies                         2011-04-21   0001193125-11-1043…   │
│    10-Q        Quarterly report for public companies                         2011-01-19   0001193125-11-0101…   │
│    10-Q        Quarterly report for public companies                         2010-07-21   0001193125-10-1628…   │
│    10-Q        Quarterly report for public companies                         2010-04-21   0001193125-10-0889…   │
│    10-Q        Quarterly report for public companies                         2010-01-25   0001193125-10-0120…   │
│    10-Q        Quarterly report for public companies                         2009-07-22   0001193125-09-1531…   │
│    10-Q/A      Quarterly report for public companies                         2009-04-27   0001193125-09-0876…   │
│                                                                                                                 │
│                                                                                                                 │
│                                                                                                                 │
│ Showing 1 to 50 of 97 filings. Page using ← prev() and next() →                                                 │
╰─────────────────────────────── Company filings between 1994-01-26 and 2025-08-01 ───────────────────────────────╯

# Get metadata of the filings

In [13]:
filings.to_pandas().sample(10)

,accession_number,filing_date,reportDate,acceptanceDateTime,act,form,fileNumber,items,size,isXBRL,isInlineXBRL,primaryDocument,primaryDocDescription
69,0001047469-03-004566,2003-02-10,2002-12-28,2003-02-10 21:43:14+00:00,,10-Q,000-10030,,392967,0,0,a2102387z10-q.htm,10-Q
84,0000320193-98-000003,1998-02-09,1997-12-26,1998-02-09 05:00:00+00:00,,10-Q,000-10030,,139805,0,0,,
27,0001628280-16-017809,2016-07-27,2016-06-25,2016-07-27 20:32:36+00:00,34,10-Q,001-36743,,9797615,1,0,a10-qq320166252016.htm,10-Q
25,0001628280-17-004790,2017-05-03,2017-04-01,2017-05-03 20:32:23+00:00,34,10-Q,001-36743,,9684229,1,0,a10-qq22017412017.htm,10-Q
6,0000320193-23-000077,2023-08-04,2023-07-01,2023-08-03 22:04:43+00:00,34,10-Q,001-36743,,5939898,1,1,aapl-20230701.htm,10-Q
76,0000912057-00-033901,2000-07-31,2000-07-01,2000-07-31 04:00:00+00:00,,10-Q,000-10030,,243400,0,0,a10-q.txt,10-Q
26,0001628280-17-000717,2017-02-01,2016-12-31,2017-02-01 21:33:29+00:00,34,10-Q,001-36743,,8206325,1,0,a10-qq1201712312016.htm,10-Q
43,0001193125-11-104388,2011-04-21,2011-03-26,2011-04-21 10:13:41+00:00,34,10-Q,000-10030,,7192927,1,0,d10q.htm,FORM 10-Q
8,0000320193-23-000006,2023-02-03,2022-12-31,2023-02-02 23:01:30+00:00,34,10-Q,001-36743,,5915088,1,1,aapl-20221231.htm,10-Q
56,0001104659-07-037745,2007-05-10,2007-03-31,2007-05-10 01:38:58+00:00,34,10-Q,000-10030,,1317107,0,0,a07-13266_110q.htm,10-Q

In [14]:
lastest_10_q = filings.latest()
lastest_10_q

╭─────────────────── Form 10-Q Apple Inc. [320193]  ────────────────────╮
│                                                                       │
│   Accession Number       Filing Date   Period of Report   Documents   │
│  ───────────────────────────────────────────────────────────────────  │
│   0000320193-25-000073   2025-08-01    2025-06-28         60          │
│                                                                       │
│                                                                       │
╰──────────────── Quarterly report for public companies ────────────────╯

In [15]:
ten_q = lastest_10_q.obj()
ten_q

╭──────────────────────────────────────────────── Apple Inc. 10-Q ────────────────────────────────────────────────╮
│ Period ending June 28, 2025 filed on August 01, 2025                                                            │
│                                                                                                                 │
│                                                                                                                 │
│ 📄                                                                                                              │
│ ├── PART I                                                                                                      │
│ │   ├── Item 1  Financial Statements                                                                            │
│ │   ├── Item 2  Management’s Discussion and Analysis of Financial Condition and Results of Operations (MD&A)    │
│ │   ├── Item 3  Quantitative and Qualitative Disclosures About Market Risk                                      │
│ │   └── Item 4  Controls and Procedures                                                                         │
│ └── PART II                                                                                                     │
│     ├── Item 1  Legal Proceedings                                                                               │
│     ├── Item 1A Risk Factors                                                                                    │
│     ├── Item 2  Unregistered Sales of Equity Securities and Use of Proceeds                                     │
│     ├── Item 3  Defaults Upon Senior Securities                                                                 │
│     ├── Item 4  Mine Safety Disclosures                                                                         │
│     ├── Item 5  Other Information                                                                               │
│     └── Item 6  Exhibits                                                                                        │
│                                                                                                                 │
│                                                                                                                 │
│ ╭─────────────────────────────────────────────── XBRL Document ───────────────────────────────────────────────╮ │
│ │            Entity Information                                                                               │ │
│ │                                                                                                             │ │
│ │   Property                   Value                                                                          │ │
│ │  ───────────────────────────────────────                                                                    │ │
│ │   entity_name                Apple Inc.                                                                     │ │
│ │   ticker                     AAPL                                                                           │ │
│ │   identifier                 320193                                                                         │ │
│ │   document_type              10-Q                                                                           │ │
│ │   reporting_end_date         2025-07-18                                                                     │ │
│ │   document_period_end_date   2025-06-28                                                                     │ │
│ │   fiscal_year                2025                                                                           │ │
│ │   fiscal_period              Q3                                                                             │ │
│ │   fiscal_year_end_month      9                                                                              │ │
│ │   fiscal_year_end_day        27                                                                             │ │
│ │   annual_report              False                                                                          │ │
│ │   quarterly_report           True                                                                           │ │
│ │   amendment                  False                                                                          │ │
│ │                                                                                                             │ │
│ │                                            Financial Statements                                             │ │
│ │                                                                                                             │ │
│ │   Type                        Definition                                                         Elements   │ │
│ │  ─────────────────────────────────────────────────────────────────────────────────────────────────────────  │ │
│ │   CoverPage                   CoverPage                                                          43         │ │
│ │   IncomeStatement             CONDENSEDCONSOLIDATEDSTATEMENTSOFOPERATIONSUnaudited               25         │ │
│ │   ComprehensiveIncome         CONDENSEDCONSOLIDATEDSTATEMENTSOFCOMPREHENSIVEINCOMEUnaudited      17         │ │
│ │   BalanceSheet                CONDENSEDCONSOLIDATEDBALANCESHEETSUnaudited                        36         │ │
│ │   BalanceSheetParenthetical   CONDENSEDCONSOLIDATEDBALANCESHEETSUnauditedParenthetical           5          │ │
│ │   StatementOfEquity           CONDENSEDCONSOLIDATEDSTATEMENTSOFSHAREHOLDERSEQUITYUnaudited       18         │ │
│ │   CashFlowStatement           CONDENSEDCONSOLIDATEDSTATEMENTSOFCASHFLOWSUnaudited                35         │ │
│ │   AccountingPolicies          SummaryofSignificantAccountingPolicies                             2          │ │
│ │   Other                       Revenue                                                            2          │ │
│ │   Other                       EarningsPerShare                                                   2          │ │
│ │   Other                       FinancialInstruments                                               2          │ │
│ │   Other                       CondensedConsolidatedFinancialStatementDetails                     2          │ │
│ │   Other                       Debt                                                               2          │ │
│ │   Other                       ShareholdersEquity                                                 2          │ │
│ │   Other                       ShareBasedCompensation                                             2          │ │
│ │   Other                       Contingencies                                                      2          │ │
│ │   SegmentDisclosure           SegmentInformationandGeographicData                                2          │ │
│ │   AccountingPolicies          SummaryofSignificantAccountingPoliciesPolicies                     4          │ │
│ │   Other                       RevenueTables                                                      2          │ │
│ │   Other                       EarningsPerShareTables                                             2          │ │
│ │   Other                       FinancialInstrumentsTables                                         3          │ │
│ │   Other                       CondensedConsolidatedFinancialStatementDetailsTables               3          │ │
│ │   Other                       DebtTables                                                         2          │ │
│ │   Other                       ShareBasedCompensationTables                                       3          │ │
│ │   SegmentDisclosure           SegmentInformationandGeographicDataTables                          3          │ │
│ │   Other                       RevenueDisaggregatedNetSalesandPortionofNetSalesThatWasPrevious…   12         │ │
│ │   Other                       RevenueAdditionalInformationDetails                                2          │ │
│ │   Other                       RevenueDeferredRevenueExpectedTimingofRealizationDetails           6          │ │
│ │   Other                       EarningsPerShareComputationofBasicandDilutedEarningsPerShareDet…   9          │ │
│ │   Other                       FinancialInstrumentsCashCashEquivalentsandMarketableSecuritiesD…   41         │ │
│ │   Other                       FinancialInstrumentsAdditionalInformationDetails                   34         │ │
│ │   Other                       FinancialInstrumentsNotionalAmountsofDerivativeInstrumentsDetai…   12         │ │
│ │   Other                       CondensedConsolidatedFinancialStatementDetailsInventoriesDetails   4          │ │
│ │   Other                       CondensedConsolidatedFinancialStatementDetailsPropertyPlantandE…   4          │ │
│ │   Other                       IncomeTaxesAdditionalInformationDetails                            6          │ │
│ │   Other                       DebtAdditionalInformationDetails                                   12         │ │
│ │   Other                       DebtSummaryofCashFlowsAssociatedwithCommercialPaperDetails         6          │ │
│ │   Other                       ShareholdersEquityAdditionalInformationDetails                     4          │ │
│ │   Other                       ShareBasedCompensationRestrictedStockUnitActivityandRelatedInfo…   16         │ │
│ │   Other                       ShareBasedCompensationAdditionalInformationDetails                 9          │ │
│ │   Other                       ShareBasedCompensationSummaryofShareBasedCompensationExpenseand…   3          │ │
│ │   SegmentDisclosure           SegmentInformationandGeographicDataInformationbyReportableSegme…   12         │ │
│ │   SegmentDisclosure           SegmentInformationandGeographicDataReconciliationofSegmentOpera…   11         │ │
│ │   Disclosures                 AwardTimingDisclosure                                              20         │ │
│ │   Disclosures                 ErrCompDisclosure                                                  20         │ │
│ │   Disclosures                 PvpDisclosure                                                      54         │ │
│ │   Other                       InsiderTradingArrangements                                         18         │ │
│ │   Other                       InsiderTradingPoliciesProc                                         3          │ │
│ │                                                                                                             │ │
│ │      Facts Summary                                                                                          │ │
│ │                                                                                                             │ │
│ │   Category      Count                                                                                       │ │
│ │  ─────────────────────                                                                                      │ │
│ │   Total Facts   769                                                                                         │ │
│ │   Contexts      165                                                                                         │ │
│ │   Units         6                                                                                           │ │
│ │   Elements      458                                                                                         │ │
│ │                                                                                                             │ │
│ │            Reporting Periods                                                                                │ │
│ │                                                                                                             │ │
│ │   Type       Period                                                                                         │ │
│ │  ─────────────────────────────────────                                                                      │ │
│ │   Instant    2025-07-18                                                                                     │ │
│ │   Instant    2025-06-28                                                                                     │ │
│ │   Duration   2024-09-29 to 2025-06-28                                                                       │ │
│ │   Duration   2025-03-30 to 2025-06-28                                                                       │ │
│ │   Instant    2025-03-29                                                                                     │ │
│ │   Instant    2024-09-28                                                                                     │ │
│ │   Duration   2023-10-01 to 2024-09-28                                                                       │ │
│ │   Instant    2024-06-29                                                                                     │ │
│ │   Duration   2024-03-31 to 2024-06-29                                                                       │ │
│ │   Duration   2023-10-01 to 2024-06-29                                                                       │ │
│ │   Instant    2024-03-30                                                                                     │ │
│ │   Instant    2023-09-30                                                                                     │ │
│ │                                                                                                             │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

In [16]:
ten_q.items

['Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 1A', 'Item 5', 'Item 6']

In [17]:
ten_q['Item 1']

'Item 1.    Financial Statements\nApple Inc.\nCONDENSED CONSOLIDATED STATEMENTS OF OPERATIONS (Unaudited)\n(In millions, except number of shares, which are reflected in thousands, and per-share amounts)\n\n                                                                                       Three Months Ended                                     Nine Months Ended\n                                                             June 28,                            June 29,             June 28,                         June 29,\n                                                                 2025                                2024                 2025                             2024\nNet sales:                                                                                                                                                     \nProducts                                                 $66,613                             $61,564             $233,287                         $224,908     \nServices                                                  27,423                              24,213               80,408                           71,197     \nTotal net sales                                           94,036                              85,777              313,695                          296,105     \nCost of sales:                                                                                                                                                 \nProducts                                                  43,620                              39,803              147,097                          140,667     \nServices                                                   6,698                               6,296               19,738                           18,634     \nTotal cost of sales                                       50,318                              46,099              166,835                          159,301     \nGross margin                                              43,718                              39,678              146,860                          136,804     \nOperating expenses:                                                                                                                                            \nResearch and development                                   8,866                               8,006               25,684                           23,605     \nSelling, general and administrative                        6,650                               6,320               20,553                           19,574     \nTotal operating expenses                                  15,516                              14,326               46,237                           43,179     \nOperating income                                          28,202                              25,352              100,623                           93,625     \nOther income/(expense), net                                (171)        142                                         (698)        250                           \nIncome before provision for income taxes                  28,031                              25,494               99,925                           93,875     \nProvision for income taxes                                 4,597                               4,046               15,381                           14,875     \nNet income                                               $23,434                             $21,448              $84,544                          $79,000     \nEarnings per share:                                                                                                                                            \nBasic                                                      $1.57                               $1.40                $5.64                            $5.13     \nDiluted                                                    $1.57                               $1.40                $5.62                            $5.11     \nShares used in computing earnings per share:                                                                                                                   \nBasic                                                 14,902,886                          15,287,521           14,992,898                       15,401,047     \nDiluted                                               14,948,179                          15,348,175           15,051,726                       15,463,175     \nSee accompanying Notes to Condensed Consolidated Financial Statements.\nApple Inc. | Q3 2025 Form 10-Q | 1\n\n\nApple Inc.\nCONDENSED CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME (Unaudited)\n(In millions)\n\n                                                                                                                Three Months Ended                                      Nine Months Ended\n                                                                                          June 28,                        June 29,                  June 28,                     June 29,\n                                                                                              2025                            2024                      2025                         2024\nNet income                                                                            $23,434                         $21,448                   $84,544                      $79,000     \nOther comprehensive income/(loss):                                                                                                                                                       \nChange in foreign currency translation, net of tax                                        449                            (73)                      (86)                         (87)     \nChange in unrealized gains/losses on derivative instruments, net of tax:                                                                                                                 \nChange in fair value of derivative instruments                                          (523)                             406                       810                          331     \nAdjustment for net (gains)/losses realized and included in net income                   (571)                            (87)                     (415)                        (678)     \nTotal change in unrealized gains/losses on derivative instruments                     (1,094)                             319                       395                        (347)     \nChange in unrealized gains/losses on marketable debt securities, net of tax:                                                                                                             \nChange in fair value of marketable debt securities                                        640                             268                        90                        3,306     \nAdjustment for net (gains)/losses realized and included in net income                     (1)                              30                       404                          164     \nTotal change in unrealized gains/losses on marketable debt securities                     639                             298                       494                        3,470     \nTotal other comprehensive income/(loss)                                                   (6)                             544                       803                        3,036     \nTotal comprehensive income                                                            $23,428                         $21,992                   $85,347                      $82,036     \nSee accompanying Notes to Condensed Consolidated Financial Statements.\nApple Inc. | Q3 2025 Form 10-Q | 2\n\n\nApple Inc.\nCONDENSED CONSOLIDATED BALANCE SHEETS (Unaudited)\n(In millions, except number of shares, which are reflected in thousands, and par value)\n\n                                                                                                                                                                                    June 28,                          September 28,\n                                                                                                                                                                                        2025                                   2024\nASSETS:                                                                                                                                                                                                                            \nCurrent assets:                                                                                                                                                                                                                    \nCash and cash equivalents                                                                                                                                                      $36,269                               $29,943       \nMarketable securities                                                                                                                                                           19,103                                35,228       \nAccounts receivable, net                                                                                                                                                        27,557                                33,410       \nVendor non-trade receivables                                                                                                                                                    19,278                                32,833       \nInventories                                                                                                                                                                      5,925                                 7,286       \nOther current assets                                                                                                                                                            14,359                                14,287       \nTotal current assets                                                                                                                                                           122,491                               152,987       \nNon-current assets:                                                                                                                                                                                                                \nMarketable securities                                                                                                                                                           77,614                                91,479       \nProperty, plant and equipment, net                                                                                                                                              48,508                                45,680       \nOther non-current assets                                                                                                                                                        82,882                                74,834       \nTotal non-current assets                                                                                                                                                       209,004                               211,993       \nTotal assets                                                                                                                                                                  $331,495                              $364,980       \nLIABILITIES AND SHAREHOLDERS’ EQUITY:                                                                                                                                                                                              \nCurrent liabilities:                                                                                                                                                                                                               \nAccounts payable                                                                                                                                                               $50,374                               $68,960       \nOther current liabilities                                                                                                                                                       62,499                                78,304       \nDeferred revenue                                                                                                                                                                 8,979                                 8,249       \nCommercial paper                                                                                                                                                                 9,923                                 9,967       \nTerm debt                                                                                                                                                                        9,345                                10,912       \nTotal current liabilities                                                                                                                                                      141,120                               176,392       \nNon-current liabilities:                                                                                                                                                                                                           \nTerm debt                                                                                                                                                                       82,430                                85,750       \nOther non-current liabilities                                                                                                                                                   42,115                                45,888       \nTotal non-current liabilities                                                                                                                                                  124,545                               131,638       \nTotal liabilities                                                                                                                                                              265,665                               308,030       \nCommitments and contingencies                                                                                                                                                                                                      \nShareholders’ equity:                                                                                                                                                                                                              \nCommon stock and additional paid-in capital, $0.00001 par value: 50,400,000 shares authorized; 14,856,722 and 15,116,786 shares issued and outstanding, respectively            89,806                                83,276       \nAccumulated deficit                                                                                                                                                           (17,607)                              (19,154)       \nAccumulated other comprehensive loss                                                                                                                                           (6,369)                               (7,172)       \nTotal shareholders’ equity                                                                                                                                                      65,830                                56,950       \nTotal liabilities and shareholders’ equity                                                                                                                                    $331,495                              $364,980       \nSee accompanying Notes to Condensed Consolidated Financial Statements.\nApple Inc. | Q3 2025 Form 10-Q | 3\n\n\nApple Inc.\nCONDENSED CONSOLIDATED STATEMENTS OF SHAREHOLDERS’ EQUITY (Unaudited)\n(In millions, except per-share amounts)\n\n                                                                                                              Three Months Ended                                          Nine Months Ended\n                                                                                      June 28,                          June 29,                    June 28,                       June 29,\n                                                                                          2025                              2024                        2025                           2024\nTotal shareholders’ equity, beginning balances                                    $66,796                           $74,194                     $56,950                        $62,146     \nCommon stock and additional paid-in capital:                                                                                                                                               \nBeginning balances                                                                 88,711                            78,815                      83,276                         73,812     \nCommon stock issued                                                                     —                                 —                         825        752                         \nCommon stock withheld related to net share settlement of equity awards            (2,163)                           (1,920)                     (4,260)                        (3,802)     \nShare-based compensation                                                            3,258                             2,955                       9,965                          9,088     \nEnding balances                                                                    89,806                            79,850                      89,806                         79,850     \nRetained earnings/(Accumulated deficit):                                                                                                                                                   \nBeginning balances                                                               (15,552)                             4,339                    (19,154)                          (214)     \nNet income                                                                         23,434                            21,448                      84,544                         79,000     \nDividends and dividend equivalents declared                                       (3,912)                           (3,864)                    (11,525)                       (11,384)     \nCommon stock withheld related to net share settlement of equity awards              (411)                             (428)                     (1,598)                        (1,517)     \nCommon stock repurchased                                                         (21,166)                          (26,221)                    (69,874)                       (70,611)     \nEnding balances                                                                  (17,607)                           (4,726)                    (17,607)                        (4,726)     \nAccumulated other comprehensive loss:                

In [18]:
ten_q['Item 2']

'Item 2.    Management’s Discussion and Analysis of Financial Condition and Results of Operations\nThis Item and other sections of this Quarterly Report on Form 10-Q (“Form 10-Q”) contain forward-looking statements, within the meaning of the Private Securities Litigation Reform Act of 1995, that involve risks and uncertainties. Forward-looking statements provide current expectations of future events based on certain assumptions and include any statement that does not directly relate to any historical or current fact. For example, statements in this Form 10-Q regarding the potential future impact of macroeconomic conditions and tariffs and other measures on the Company’s business and results of operations are forward-looking statements. Forward-looking statements can also be identified by words such as “future,” “anticipates,” “believes,” “estimates,” “expects,” “intends,” “plans,” “predicts,” “will,” “would,” “could,” “can,” “may,” and similar terms. Forward-looking statements are not guarantees of future performance and the Company’s actual results may differ significantly from the results discussed in the forward-looking statements. Factors that might cause such differences include, but are not limited to, those discussed in Part I, Item 1A of the 2024 Form 10-K and Part II, Item 1A of this Form 10-Q, in each case under the heading “Risk Factors.” The Company assumes no obligation to revise or update any forward-looking statements for any reason, except as required by law.\nUnless otherwise stated, all information presented herein is based on the Company’s fiscal calendar, and references to particular years, quarters, months or periods refer to the Company’s fiscal years ended in September and the associated quarters, months and periods of those fiscal years.\nThe following discussion should be read in conjunction with the 2024 Form 10-K filed with the U.S. Securities and Exchange Commission (the “SEC”) and the condensed consolidated financial statements and accompanying notes included in Part I, Item 1 of this Form 10-Q.\nAvailable Information\nThe Company periodically provides certain information for investors on its corporate website, www.apple.com, and its investor relations website, investor.apple.com. This includes press releases and other information about financial performance, information on corporate governance, and details related to the Company’s annual meeting of shareholders. The information contained on the websites referenced in this Form 10-Q is not incorporated by reference into this filing. Further, the Company’s references to website URLs are intended to be inactive textual references only.\nBusiness Seasonality and Product Introductions\nThe Company has historically experienced higher net sales in its first quarter compared to other quarters in its fiscal year due in part to seasonal holiday demand. Additionally, new product and service introductions can significantly impact net sales, cost of sales and operating expenses. The timing of product introductions can also impact the Company’s net sales to its indirect distribution channels as these channels are filled with new inventory following a product launch, and channel inventory of an older product often declines as the launch of a newer product approaches. Net sales can also be affected when consumers and distributors anticipate a product introduction.\nDuring the third quarter of 2025, the Company announced iOS 26, macOS® Tahoe 26, iPadOS® 26, watchOS® 26, visionOS® 26 and tvOS® 26.\nMacroeconomic Conditions\nMacroeconomic conditions, including inflation, interest rates and currency fluctuations, have directly and indirectly impacted, and could in the future materially impact, the Company’s results of operations and financial condition.\nApple Inc. | Q3 2025 Form 10-Q | 13\n\n\nTariffs and Other Measures\nBeginning in the second quarter of 2025, new tariffs were announced on imports to the U.S. (“U.S. Tariffs”), including additional tariffs on imports from China, India, Japan, South Korea, Taiwan, Vietnam and the European Union (“EU”), among others. In response, several countries have imposed, or threatened to impose, reciprocal tariffs on imports from the U.S. and other retaliatory measures. Various modifications to the U.S. Tariffs have been announced and further changes could be made in the future, which may include additional sector-based tariffs or other measures. For example, the U.S. Department of Commerce has initiated an investigation under Section 232 of the Trade Expansion Act of 1962, as amended, into, among other things, imports of semiconductors, semiconductor manufacturing equipment, and their derivative products, including downstream products that contain semiconductors. Tariffs and other measures that are applied to the Company’s products or their components can have a material adverse impact on the Company’s business, results of operations and financial condition, including impacting the Company’s supply chain, the availability of rare earths and other raw materials and components, pricing and gross margin. The ultimate impact remains uncertain and will depend on several factors, including whether additional or incremental U.S. Tariffs or other measures are announced or imposed, to what extent other countries implement tariffs or other retaliatory measures in response, and the overall magnitude and duration of these measures. Trade and other international disputes can have an adverse impact on the overall macroeconomic environment and result in shifts and reductions in consumer spending and negative consumer sentiment for the Company’s products and services, all of which can further adversely affect the Company’s business and results of operations.\nSegment Operating Performance\nThe following table shows net sales by reportable segment for the three- and nine-month periods ended June 28, 2025 and June 29, 2024 (dollars in millions):\n\n                                                                               Three Months Ended                                                            Nine Months Ended\n                                 June 28,                     June 29,                     Change           June 28,                       June 29,                     Change\n                                     2025                         2024                                          2025                           2024                           \nAmericas                     $41,198                      $37,678                          9    %      $134,161                       $125,381                          7    %\nEurope                        24,014                       21,884                         10    %        82,329                         76,404                          8    %\nGreater China                 15,369                       14,728                          4    %        49,884                         51,919                        (4)    %\nJapan                          5,782                        5,097                         13    %        22,067                         19,126                         15    %\nRest of Asia Pacific           7,673                        6,390                         20    %        25,254                         23,275                          9    %\nTotal net sales              $94,036                      $85,777                         10    %      $313,695                       $296,105                          6    %\nAmericas\nAmericas net sales increased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due primarily to higher net sales of iPhone and Services. The weakness in foreign currencies relative to the U.S. dollar had an unfavorable year-over-year impact on Americas net sales during the third quarter and first nine months of 2025.\nEurope\nEurope net sales increased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due primarily to higher net sales of Services and iPhone.\nGreater China\nGreater China net sales increased during the third quarter of 2025 compared to the third quarter of 2024 due primarily to higher net sales of iPhone and Mac. Greater China net sales decreased during the first nine months of 2025 compared to the same period in 2024 due to lower net sales of iPhone, partially offset by higher net sales of Mac.\nJapan\nJapan net sales increased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due primarily to higher net sales of iPhone and Services. The strength in the yen relative to the U.S. dollar had a favorable year-over-year impact on Japan net sales during the third quarter of 2025.\nRest of Asia Pacific\nRest of Asia Pacific net sales increased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due primarily to higher net sales of Services and iPhone.\nApple Inc. | Q3 2025 Form 10-Q | 14\n\n\nProducts and Services Performance\nThe following table shows net sales by category for the three- and nine-month periods ended June 28, 2025 and June 29, 2024 (dollars in millions):\n\n                                                                                           Three Months Ended                                                            Nine Months Ended\n                                             June 28,                     June 29,                     Change           June 28,                       June 29,                     Change\n                                                 2025                         2024                                          2025                           2024                           \niPhone                                   $44,582                      $39,296                         13    %      $160,561                       $154,961                          4    %\nMac                                        8,046                        7,009                         15    %        24,982                         22,240                         12    %\niPad                                       6,581                        7,162                        (8)    %        21,071                         19,744                          7    %\nWearables, Home and Accessories            7,404                        8,097                        (9)    %        26,673                         27,963                        (5)    %\nServices                                  27,423                       24,213                         13    %        80,408                         71,197                         13    %\nTotal net sales                          $94,036                      $85,777                         10    %      $313,695                       $296,105                          6    %\niPhone\niPhone net sales increased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due to higher net sales of Pro models.\nMac\nMac net sales increased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due to higher net sales of both laptops and desktops.\niPad\niPad net sales decreased during the third quarter of 2025 compared to the third quarter of 2024 due to lower net sales of iPad Pro®, partially offset by higher net sales of all other iPad models. iPad net sales increased during the first nine months of 2025 compared to the same period in 2024 due primarily to higher net sales of iPad Air®.\nWearables, Home and Accessories\nWearables, Home and Accessories net sales decreased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due primarily to lower net sales of Wearables and Accessories.\nServices\nServices net sales increased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due primarily to higher net sales from advertising, the App Store® and cloud services.\nApple Inc. | Q3 2025 Form 10-Q | 15\n\n\nGross Margin\nProducts and Services gross margin and gross margin percentage for the three- and nine-month periods ended June 28, 2025 and June 29, 2024, were as follows (dollars in millions):\n\n                                                       Three Months Ended                                 Nine Months Ended\n                                 June 28,                        June 29,           June 28,                       June 29,\n                                     2025                            2024               2025                           2024\nGross margin:                                                                                                              \nProducts                     $22,993                         $21,761            $86,190                        $84,241     \nServices                      20,725                          17,917             60,670                         52,563     \nTotal gross margin           $43,718                         $39,678           $146,860                       $136,804     \n\nGross margin percentage:                                                                                \nProducts                               34.5   %           35.3   %           36.9   %           37.5   %\nServices                               75.6   %           74.0   %           75.5   %           73.8   %\nTotal gross margin percentage          46.5   %           46.3   %           46.8   %           46.2   %\nProducts Gross Margin\nProducts gross margin increased during the third quarter of 2025 compared to the third quarter of 2024 due primarily to a different mix of products and favorable costs, partially offset by tariffs. Products gross margin increased during the first nine months of 2025 compared to the same period in 2024 due primarily to favorable costs and a different mix of products, partially offset by tariffs and the weakness in foreign currencies relative to the U.S. dollar.\nProducts gross margin percentage decreased during the third quarter of 2025 compared to the third quarter of 2024 due primarily to tariffs and a different mix of products, partially offset by favorable costs. Products gross margin percentage decreased during the first nine months of 2025 compared to the same period in 2024 due primarily to a different mix of products and tariffs, partially offset by favorable costs.\nServices Gross Margin\nServices gross margin increased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due primarily to higher Services net sales and a different mix of services.\nServices gross margin percentage increased during the third quarter and first nine months of 2025 compared to the same periods in 2024 due primarily to a different mix of services, partially offset by higher costs.\nThe Company’s future gross margins can be impacted by a variety of factors, as discussed in Part I, Item 1A of the 2024 Form 10-K and Part II, Item 1A of this Form 10-Q, in each case under the heading “Risk Factors.” As a result, the Company believes, in general, gross margins will be subject to volatility and downward pressure.\nApple Inc. | Q3 2025 Form 10-Q | 16\n\n\nOperating Expenses\nOperating expenses for the three- and nine-month periods ended June 28, 2025 and June 29, 2024, were as follows (dollars in millions):\n\n                                                                      Three Months Ended                                      Nine Months Ended\n                                                June 28,                        June 29,                  June 28,                     June 29,\n                                                    2025                            2024                      2025                         2024\nResearch and development                     $8,866                          $8,006                   $25,684                      $23,605     \nPercentage of total net sales                     9    %                          9    %                    8    %                       8    %\nSelling, general and administrative          $6,650                          $6,320                   $20,553                      $19,574     \nPercentage of total net sales                     7    %                          7    %                    7    %                       7    %\nTotal operating expenses                    $15,516                         $14,326                   $46,237                      $43,179     \nPercentage of total net sales                    17    %                         17    %                   15    %                      15    %\nResearch and Development\nThe growth in research and development (“R&D”) expense during the third quarter and first nine months of 2025 compared to the same periods in 2024 was driven primarily by increases in headcount-related expenses and infrastructure-related costs.\nSelling, General and Administrative\nThe growth in selling, general and administrative expense during the third quarter and first nine months of 2025 compared to the same periods in 2024 was driven primarily by increases in headcount-related expenses and variable selling expenses.\nProvision for Income Taxes\nProvision for income taxes, effective tax rate and statutory federal income tax rate for the three- and nine-month periods ended June 28, 2025 and June 29, 2024, were as follows (dollars in millions):\n\n                                                                      Three Months Ended                                      Nine Months Ended\n                                                June 28,                        June 29,                  June 28,                     June 29,\n                                                    2025                            2024                      2025                         2024\nProvision for income taxes                   $4,597                          $4,046                   $15,381                      $14,875     \nEffective tax rate                             16.4    %                       15.9    %                 15.4    %                    15.8    %\nStatutory federal income tax rate                21    %                         21    %                   21    %                      21    %\nThe Company’s effective tax rate for the third quarter of 2025 was lower than the statutory federal income tax rate due primarily to a lower effective tax rate on foreign earnings, the impact of the U.S. federal R&D credit, and tax benefits from share-based compensation, partially offset by state income taxes. The Company’s effective tax rate for the first nine months of 2025 was lower than the statutory federal income tax rate due primarily to a lower effective tax rate on foreign earnings, including the impact of changes in unrecognized tax benefits, tax benefits from share-based compensation, and the impact of the U.S. federal R&D credit, partially offset by state income taxes.\nThe Company’s effective tax rate for the third quarter of 2025 was higher compared to the third quarter of 2024 due primarily to the impact from foreign currency revaluations of unrecognized tax benefits. The Company’s effective tax rate for the first nine months of 2025 was lower compared to the same period in 2024 due primarily to the impact of changes in unrecognized tax benefits, partially offset by a higher effective tax rate on foreign earnings.\nApple Inc. | Q3 2025 Form 10-Q | 17\n\n\nLiquidity and Capital Resources\nThe Company believes its balances of cash, cash equivalents and marketable securities, along with cash generated by ongoing operations and continued access to debt markets, will be sufficient to satisfy its cash requirements and capital return program over the next 12 months and beyond.\nThe Company’s contractual cash requirements have not

# Access the parse format

In [19]:
xbrl = lastest_10_q.xbrl()
xbrl

╭───────────────────────────────────────────────── XBRL Document ─────────────────────────────────────────────────╮
│            Entity Information                                                                                   │
│                                                                                                                 │
│   Property                   Value                                                                              │
│  ───────────────────────────────────────                                                                        │
│   entity_name                Apple Inc.                                                                         │
│   ticker                     AAPL                                                                               │
│   identifier                 320193                                                                             │
│   document_type              10-Q                                                                               │
│   reporting_end_date         2025-07-18                                                                         │
│   document_period_end_date   2025-06-28                                                                         │
│   fiscal_year                2025                                                                               │
│   fiscal_period              Q3                                                                                 │
│   fiscal_year_end_month      9                                                                                  │
│   fiscal_year_end_day        27                                                                                 │
│   annual_report              False                                                                              │
│   quarterly_report           True                                                                               │
│   amendment                  False                                                                              │
│                                                                                                                 │
│                                              Financial Statements                                               │
│                                                                                                                 │
│   Type                        Definition                                                             Elements   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   CoverPage                   CoverPage                                                              43         │
│   IncomeStatement             CONDENSEDCONSOLIDATEDSTATEMENTSOFOPERATIONSUnaudited                   25         │
│   ComprehensiveIncome         CONDENSEDCONSOLIDATEDSTATEMENTSOFCOMPREHENSIVEINCOMEUnaudited          17         │
│   BalanceSheet                CONDENSEDCONSOLIDATEDBALANCESHEETSUnaudited                            36         │
│   BalanceSheetParenthetical   CONDENSEDCONSOLIDATEDBALANCESHEETSUnauditedParenthetical               5          │
│   StatementOfEquity           CONDENSEDCONSOLIDATEDSTATEMENTSOFSHAREHOLDERSEQUITYUnaudited           18         │
│   CashFlowStatement           CONDENSEDCONSOLIDATEDSTATEMENTSOFCASHFLOWSUnaudited                    35         │
│   AccountingPolicies          SummaryofSignificantAccountingPolicies                                 2          │
│   Other                       Revenue                                                                2          │
│   Other                       EarningsPerShare                                                       2          │
│   Other                       FinancialInstruments                                                   2          │
│   Other                       CondensedConsolidatedFinancialStatementDetails                         2          │
│   Other                       Debt                                                                   2          │
│   Other                       ShareholdersEquity                                                     2          │
│   Other                       ShareBasedCompensation                                                 2          │
│   Other                       Contingencies                                                          2          │
│   SegmentDisclosure           SegmentInformationandGeographicData                                    2          │
│   AccountingPolicies          SummaryofSignificantAccountingPoliciesPolicies                         4          │
│   Other                       RevenueTables                                                          2          │
│   Other                       EarningsPerShareTables                                                 2          │
│   Other                       FinancialInstrumentsTables                                             3          │
│   Other                       CondensedConsolidatedFinancialStatementDetailsTables                   3          │
│   Other                       DebtTables                                                             2          │
│   Other                       ShareBasedCompensationTables                                           3          │
│   SegmentDisclosure           SegmentInformationandGeographicDataTables                              3          │
│   Other                       RevenueDisaggregatedNetSalesandPortionofNetSalesThatWasPreviouslyDe…   12         │
│   Other                       RevenueAdditionalInformationDetails                                    2          │
│   Other                       RevenueDeferredRevenueExpectedTimingofRealizationDetails               6          │
│   Other                       EarningsPerShareComputationofBasicandDilutedEarningsPerShareDetails    9          │
│   Other                       FinancialInstrumentsCashCashEquivalentsandMarketableSecuritiesDetai…   41         │
│   Other                       FinancialInstrumentsAdditionalInformationDetails                       34         │
│   Other                       FinancialInstrumentsNotionalAmountsofDerivativeInstrumentsDetails      12         │
│   Other                       CondensedConsolidatedFinancialStatementDetailsInventoriesDetails       4          │
│   Other                       CondensedConsolidatedFinancialStatementDetailsPropertyPlantandEquip…   4          │
│   Other                       IncomeTaxesAdditionalInformationDetails                                6          │
│   Other                       DebtAdditionalInformationDetails                                       12         │
│   Other                       DebtSummaryofCashFlowsAssociatedwithCommercialPaperDetails             6          │
│   Other                       ShareholdersEquityAdditionalInformationDetails                         4          │
│   Other                       ShareBasedCompensationRestrictedStockUnitActivityandRelatedInformat…   16         │
│   Other                       ShareBasedCompensationAdditionalInformationDetails                     9          │
│   Other                       ShareBasedCompensationSummaryofShareBasedCompensationExpenseandtheR…   3          │
│   SegmentDisclosure           SegmentInformationandGeographicDataInformationbyReportableSegmentDe…   12         │
│   SegmentDisclosure           SegmentInformationandGeographicDataReconciliationofSegmentOperating…   11         │
│   Disclosures                 AwardTimingDisclosure                                                  20         │
│   Disclosures                 ErrCompDisclosure                                                      20         │
│   Disclosures                 PvpDisclosure                                                          54         │
│   Other                       InsiderTradingArrangements                                             18         │
│   Other                       InsiderTradingPoliciesProc                                             3          │
│                                                                                                                 │
│      Facts Summary                                                                                              │
│                                                                                                                 │
│   Category      Count                                                                                           │
│  ─────────────────────                                                                                          │
│   Total Facts   769                                                                                             │
│   Contexts      165                                                                                             │
│   Units         6                                                                                               │
│   Elements      458                                                                                             │
│                                                                                                                 │
│            Reporting Periods                                                                                    │
│                                                                                                                 │
│   Type       Period                                                                                             │
│  ─────────────────────────────────────                                                                          │
│   Instant    2025-07-18                                                                                         │
│   Instant    2025-06-28                                                                                         │
│   Duration   2024-09-29 to 2025-06-28                                                                           │
│   Duration   2025-03-30 to 2025-06-28                                                                           │
│   Instant    2025-03-29                                                                                         │
│   Instant    2024-09-28                                                                                         │
│   Duration   2023-10-01 to 2024-09-28                                                                           │
│   Instant    2024-06-29                                                                                         │
│   Duration   2024-03-31 to 2024-06-29                                                                           │
│   Duration   2023-10-01 to 2024-06-29                                                                           │
│   Instant    2024-03-30                                                                                         │
│   Instant    2023-09-30                                                                                         │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

# Get filings

In [28]:
apple_income_statement = get_filings(year=2024, quarter=1, form='10-K')
apple_income_statement

╭────────────────────────────────────────────────── SEC Filings ──────────────────────────────────────────────────╮
│                                                                                                                 │
│    Form              CIK   Ticker   Company                                 Filing Date   Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    10-K          1847360   BCOW     1895 Bancorp of Wisconsin, Inc. /MD/    2024-03-29    0000950170-24-0385…   │
│    10-K           933972   SCWO     374Water Inc.                           2024-03-29    0001654954-24-0039…   │
│    10-K          1634452            AB Private Credit Investors Corp        2024-03-29    0001193125-24-0819…   │
│    10-K           738214   AMTX     AEMETIS, INC                            2024-03-29    0001437749-24-0100…   │
│    10-K          1837607   PMGM     AEON Biopharma, Inc.                    2024-03-29    0001837607-24-0000…   │
│    10-K          1280263   AMBA     AMBARELLA INC                           2024-03-29    0000950170-24-0385…   │
│    10-K          1880438   ANTX     AN2 Therapeutics, Inc.                  2024-03-29    0000950170-24-0386…   │
│    10-K          1838821   ARYD     ARYA Sciences Acquisition Corp IV       2024-03-29    0001140361-24-0163…   │
│    10-K          1868775   ASCA     ASPAC I Acquisition Corp.               2024-03-29    0001213900-24-0273…   │
│    10-K          1876716   ASCB     ASPAC II Acquisition Corp.              2024-03-29    0001213900-24-0275…   │
│    10-K          1304409   AHNR     ATHENA GOLD CORP                        2024-03-29    0001683168-24-0018…   │
│    10-K          1448597   AUGG     AUGUSTA GOLD CORP.                      2024-03-29    0001213900-24-0273…   │
│    10-K           727207   AXDX     Accelerate Diagnostics, Inc             2024-03-29    0001628280-24-0136…   │
│    10-K          1844507   AVHI     Achari Ventures Holdings Corp. I        2024-03-29    0001213900-24-0280…   │
│    10-K          1388320   ATNM     Actinium Pharmaceuticals, Inc.          2024-03-29    0001213900-24-0280…   │
│    10-K          1541157   AKTX     Akari Therapeutics Plc                  2024-03-29    0000950170-24-0386…   │
│    10-K          1849056   ALCC     AltC Acquisition Corp.                  2024-03-29    0001410578-24-0003…   │
│    10-K          1198415            Altegris Winton Futures Fund, L.P.      2024-03-29    0001683168-24-0018…   │
│    10-K          1555074   AAMC     Altisource Asset Management Corp        2024-03-29    0001555074-24-0000…   │
│    10-K          1477845   ANVS     Annovis Bio, Inc.                       2024-03-29    0001558370-24-0043…   │
│    10-K          1893219   ABP      Atlantic Coastal Acquisition Corp. II   2024-03-29    0001193125-24-0811…   │
│    10-K          1534120   AVTX     Avalo Therapeutics, Inc.                2024-03-29    0001628280-24-0137…   │
│    10-K          1706303            BANK 2017-BNK5                          2024-03-29    0001888524-24-0052…   │
│    10-K          1718322            BANK 2017-BNK8                          2024-03-29    0001888524-24-0051…   │
│    10-K          1731627            BANK 2018-BNK11                         2024-03-29    0001888524-24-0052…   │
│    10-K          1749973            BANK 2018-BNK14                         2024-03-29    0001888524-24-0051…   │
│    10-K          1769961            BANK 2019-BNK17                         2024-03-29    0001888524-24-0052…   │
│    10-K          1784958            BANK 2019-BNK20                         2024-03-29    0001888524-24-0051…   │
│    10-K          1792414            BANK 2019-BNK23                         2024-03-29    0001888524-24-0051…   │
│    10-K          1803308            BANK 2020-BNK26                         2024-03-29    0001888524-24-0053…   │
│    10-K          1830315            BANK 2020-BNK29                         2024-03-29    0001888524-24-0052…   │
│    10-K          1848411            BANK 2021-BNK32                         2024-03-29    0001888524-24-0052…   │
│    10-K          1872347            BANK 2021-BNK35                         2024-03-29    0001888524-24-0053…   │
│    10-K          1895567            BANK 2021-BNK38                         2024-03-29    0001888524-24-0053…   │
│    10-K          1920442            BANK 2022-BNK41                         2024-03-29    0001888524-24-0053…   │
│    10-K          1950141            BANK 2022-BNK44                         2024-03-29    0001888524-24-0053…   │
│    10-K          1979748            BANK5 2023-5YR2                         2024-03-29    0001888524-24-0053…   │
│    10-K          1734103            BENCHMARK 2018-B3 COMMERCIAL MORTGAG…   2024-03-29    0000950170-24-0383…   │
│    10-K          1751874            BENCHMARK 2018-B6 MORTGAGE TRUST        2024-03-29    0000950170-24-0383…   │
│    10-K          1764759            BENCHMARK 2019-B9 MORTGAGE TRUST        2024-03-29    0000950170-24-0382…   │
│    10-K          1821946            BENCHMARK 2020-B19 MORTGAGE TRUST       2024-03-29    0000950170-24-0383…   │
│    10-K          1840644            BENCHMARK 2021-B23 MORTGAGE TRUST       2024-03-29    0000950170-24-0383…   │
│    10-K          1862080            BENCHMARK 2021-B27 MORTGAGE TRUST       2024-03-29    0000950170-24-0383…   │
│    10-K          1894714            BENCHMARK 2021-B31 MORTGAGE TRUST       2024-03-29    0000950170-24-0383…   │
│    10-K          1921064            BENCHMARK 2022-B35 MORTGAGE TRUST       2024-03-29    0001888524-24-0053…   │
│    10-K          1903688            BMO 2022-C1 Mortgage Trust              2024-03-29    0001888524-24-0053…   │
│    10-K          1932997            BMO 2022-C2 Mortgage Trust              2024-03-29    0001888524-24-0053…   │
│    10-K          1942599            BMO 2022-C3 Mortgage Trust              2024-03-29    0001888524-24-0053…   │
│    10-K          1984246            BMO 2023-5C1 Mortgage Trust             2024-03-29    0001888524-24-0053…   │
│    10-K          1994754            BMO 2023-5C2 Mortgage Trust             2024-03-29    0001888524-24-0053…   │
│                                                                                                                 │
│                                                                                                                 │
│                                                                                                                 │
│ Showing 1 to 50 of 5,149 filings. Page using ← prev() and next() →                                              │
╰───────────────────────────────── SEC Filings between 2024-01-02 and 2024-03-29 ─────────────────────────────────╯

In [31]:
apple_income_statement = apple_income_statement[0]
apple_income_statement

╭──── Form 10-K 1895 Bancorp of Wisconsin, Inc. /MD/ [1847360] BCOW ────╮
│                                                                       │
│   Accession Number       Filing Date   Period of Report   Documents   │
│  ───────────────────────────────────────────────────────────────────  │
│   0000950170-24-038577   2024-03-29    2023-12-31         130         │
│                                                                       │
│                                                                       │
╰───────────────── Annual report for public companies ──────────────────╯

# Download the report

In [32]:
apple_income_statement = apple_income_statement.obj()
apple_income_statement

╭─────────────────────────────────── 1895 Bancorp of Wisconsin, Inc. /MD/ 10-K ───────────────────────────────────╮
│ Period ending December 31, 2023 filed on March 29, 2024                                                         │
│                                                                                                                 │
│                                                                                                                 │
│ 📄                                                                                                              │
│ ├── PART I                                                                                                      │
│ │   ├── Item 1  Business                                                                                        │
│ │   ├── ITEM 1A: Risk Factors                                                                                   │
│ │   ├── Item 1B Unresolved Staff Comments                                                                       │
│ │   ├── Item 2  Properties                                                                                      │
│ │   ├── Item 3  Legal Proceedings                                                                               │
│ │   └── Item 4  Mine Safety Disclosures                                                                         │
│ ├── PART II                                                                                                     │
│ │   ├── Item 5  Market for Registrant’s Common Equity                                                           │
│ │   ├── Item 6  Selected Financial Data                                                                         │
│ │   ├── Item 7  Management’s Discussion and Analysis (MD&A)                                                     │
│ │   ├── Item 7A Quantitative and Qualitative Disclosures About Market Risk                                      │
│ │   ├── Item 8  Financial Statements                                                                            │
│ │   ├── Item 9  Controls and Procedures                                                                         │
│ │   ├── Item 9A Controls and Procedures                                                                         │
│ │   ├── Item 9B Other Information                                                                               │
│ │   └── ITEM 9C: Disclosure Regarding Foreign Jurisdictions That Prevent Inspections                            │
│ ├── PART III                                                                                                    │
│ │   ├── Item 10 Directors, Executive Officers, and Corporate Governance                                         │
│ │   ├── Item 11 Executive Compensation                                                                          │
│ │   ├── Item 12 Security Ownership of Certain Beneficial Owners and Management                                  │
│ │   ├── Item 13 Certain Relationships and Related Transactions, and Director Independence                       │
│ │   └── Item 14 Principal Accounting Fees and Services                                                          │
│ └── PART IV                                                                                                     │
│     ├── Item 15 Exhibits, Financial Statement Schedules                                                         │
│     └── Item 16 Form 10-K Summary                                                                               │
│                                                                                                                 │
│                                                                                                                 │
│ ╭─────────────────────────────────────────────── XBRL Document ───────────────────────────────────────────────╮ │
│ │                       Entity Information                                                                    │ │
│ │                                                                                                             │ │
│ │   Property                   Value                                                                          │ │
│ │  ────────────────────────────────────────────────────────────                                               │ │
│ │   entity_name                1895 BANCORP OF WISCONSIN, INC.                                                │ │
│ │   ticker                     BCOW                                                                           │ │
│ │   identifier                 1847360                                                                        │ │
│ │   document_type              10-K                                                                           │ │
│ │   reporting_end_date         2024-03-20                                                                     │ │
│ │   document_period_end_date   2023-12-31                                                                     │ │
│ │   fiscal_year                2023                                                                           │ │
│ │   fiscal_period              FY                                                                             │ │
│ │   fiscal_year_end_month      12                                                                             │ │
│ │   fiscal_year_end_day        31                                                                             │ │
│ │   annual_report              True                                                                           │ │
│ │   quarterly_report           False                                                                          │ │
│ │   amendment                  False                                                                          │ │
│ │                                                                                                             │ │
│ │                                            Financial Statements                                             │ │
│ │                                                                                                             │ │
│ │   Type                             Definition                                                    Elements   │ │
│ │  ─────────────────────────────────────────────────────────────────────────────────────────────────────────  │ │
│ │   CoverPage                        CoverPage                                                     40         │ │
│ │   BalanceSheet                     ConsolidatedBalanceSheets                                     34         │ │
│ │   BalanceSheetParenthetical        ConsolidatedBalanceSheetsParenthetical                        18         │ │
│ │   IncomeStatement                  ConsolidatedStatementsOfOperations                            42         │ │
│ │   ComprehensiveIncome              StatementConsolidatedStatementsOfComprehensiveLoss            9          │ │
│ │   StatementOfEquity                ConsolidatedStatementsOfChangesInStockholdersEquity           37         │ │
│ │   StatementOfEquityParenthetical   ConsolidatedStatementsOfChangesInStockholdersEquityParenth…   6          │ │
│ │   CashFlowStatement                ConsolidatedStatementsOfCashFlows                             66         │ │
│ │   AccountingPolicies               SummaryOfSignificantAccountingPolicies                        2          │ │
│ │   Other                            CashAndDueFromBanks                                           2          │ │
│ │   Other                            AvailableForSaleSecurities                                    2          │ │
│ │   Other                            Loans                                                         2          │ │
│ │   Other                            PremisesAndEquipment                                          2          │ │
│ │   Other                            MortgageServicingRights                                       2          │ │
│ │   Other                            Deposits                                                      2          │ │
│ │   Other                            FhlbAdvancesAndOtherBorrowings                                2          │ │
│ │   Other                            EmployeeBenefitPlans                                          2          │ │
│ │   Other                            IncomeTaxes                                                   2          │ │
│ │   Other                            CommitmentsAndContingencies                                   2          │ │
│ │   Other                            ConcentrationOfCreditRisk                                     2          │ │
│ │   Other                            EmployeeStockOwnershipPlan                                    2          │ │
│ │   Other                            RelatedPartyTransactions                                      2          │ │
│ │   Other                            FairValue                                                     2          │ │
│ │   Other                            EquityAndRegulatoryMatters                                    2          │ │
│ │   Other                            DeferredCompensation                                          2          │ │
│ │   Disclosures                      DisclosureEarningsLossPerShareEps1                            2          │ │
│ │   Other                            StockBasedCompensation                                        2          │ │
│ │   Disclosures                      DisclosureParentCompanyOnlyFinancialStatements                2          │ │
│ │   AccountingPolicies               SummaryOfSignificantAccountingPoliciesPolicies                27         │ │
│ │   Other                            AvailableForSaleSecuritiesTables                              6          │ │
│ │   Other                            LoansTables                                                   13         │ │
│ │   Other                            PremisesAndEquipmentTables                                    4          │ │
│ │   Other                            MortgageServicingRightsTables                                 3          │ │
│ │   Other                            DepositsTables                                                4          │ │
│ │   Other                            FhlbAdvancesAndOtherBorrowingsTables                          3          │ │
│ │   Other                            IncomeTaxesTables                                             4          │ │
│ │   Other                            CommitmentsAndContingenciesTables                             2          │ │
│ │   Other                            EmployeeStockOwnershipPlanTable                               2          │ │
│ │   Other                            RelatedPartyTransactionsTables                                2          │ │
│ │   Other                            FairValueTables                                               4          │ │
│ │   Other                            EquityAndRegulatoryMattersTables                              2          │ │
│ │   Disclosures                      DisclosureEarningsLossPerShareEpsTables                       2          │ │
│ │   Other                            StockBasedCompensationTables                                  5          │ │
│ │   Disclosures                      DisclosureParentCompanyOnlyFinancialStatementsTables          2          │ │
│ │   AccountingPolicies               SummaryOfSignificantAccountingPoliciesAdditionalInformatio…   47         │ │
│ │   Other                            CashAndDueFromBanksAdditionalInformationDetail                10         │ │
│ │   Other                            NatureOfOperationsAndBasisOfPresentationAdditionalInformat…   20         │ │
│ │   Other                            AvailableForSaleSecuritiesSummaryOfAmortizedCostsAndFairVa…   14         │ │
│ │   Other                            AvailableForSaleSecuritiesSummaryOfGrossUnrealizedLossesOn…   16         │ │
│ │   Other                            AvailableForSaleSecuritiesSummaryOfAmortizedCostsAndFairVa…   19         │ │
│ │   Other                            AvailableForSaleSecuritiesAdditionalInformationDetail         2          │ │
│ │   Other                            AvailableForSaleSecuritiesSummaryOfProceedsFromSalesOfSecu…   5          │ │
│ │   Disclosures                      DisclosureAvailableForSaleSecuritiesSummaryOfNumberOfDebtS…   11         │ │
│ │   Other                            LoansSummaryOfMajorClassificationsOfLoansDetail               21         │ │
│ │   Other                            LoansAdditionalInformationDetail                              48         │ │
│ │   Disclosures                      DisclosureLoansSummaryOfActivityInAllowanceForLoanAndLease…   18         │ │
│ │   Disclosures                      DisclosureLoansScheduleOfComponentsOfProvisionForCreditLos…   8          │ │
│ │   Other                            LoansSummaryOfAllowanceForLoanAndLeaseLossesForLoansEvalua…   13         │ │
│ │   Disclosures                      DisclosureLoansSummaryOfAmortizedCostBasisOfLoansByCreditQ…   34         │ │
│ │   Other                            LoansSummaryOfInformationRegardingImpairedLoansDetail         19         │ │
│ │   Other                            LoansSummaryOfInternalRiskRatingsOfLoansDetail                17         │ │
│ │   Other                            LoansSummaryOfInformationRegardingTheCreditQualityIndicato…   17         │ │
│ │   Disclosures                      DisclosureLoansSummaryOfGrossChargeoffsOfLoansForPortfolio…   18         │ │
│ │   Other                            LoansScheduleOfAnalysisOfPastDueLoansDetail                   19         │ │
│ │   Disclosures                      DisclosureLoansSummaryOfInformationOnNonaccrualLoansDetail    11         │ │
│ │   Disclosures                      DisclosureLoansSummaryOfCollateralDependentLoansAndRelated…   15         │ │
│ │   Disclosures                      DisclosureLoansSummaryOfAllowanceForLoanAndLeaseLossesForL…   13         │ │
│ │   Disclosures                      DisclosureLoansSummaryOfInformationRegardingImpairedLoansD…   18         │ │
│ │   Disclosures                      DisclosurePremisesAndEquipmentSummaryOfPremisesAndEquipmen…   14         │ │
│ │   Disclosures                      DisclosurePremisesAndEquipmentAdditionalInformationDetail     15         │ │
│ │   Disclosures                      DisclosurePremisesAndEquipmentSummaryOfNetLeaseCostDetail     8          │ │
│ │   Disclosures                      DisclosurePremisesAndEquipmentSummaryOfMaturityOfRemaining…   9          │ │
│ │   Other                            MortgageServicingRightsAdditionalInformationDetail            11         │ │
│ │   Disclosures                      DisclosureMortgageServicingRightsSummaryOfChangesInBalance…   6          │ │
│ │   Other                            MortgageServicingRightsSummaryOfEstimatedFutureAmortizatio…   8          │ │
│ │   Other                            DepositsCompositionOfDepositsDetail                           7          │ │
│ │   Other                            DepositsCompositionOfDepositsParentheticalDetail              2          │ │
│ │   Other                            DepositsAdditionalInformationDetail                           3          │ │
│ │   Other                            DepositsInterestExpenseOnDepositsDetail                       6          │ │
│ │   Other                            DepositsScheduledMaturitiesOfCertificatesOfDepositDetail      8          │ │
│ │   Other                            FhlbAdvancesAndOtherBorrowingsSummaryOfFederalHomeLoanBank…   26         │ │
│ │   Other                            FhlbAdvancesAndOtherBorrowingsScheduleOfMaturitiesOfFedera…   15         │ │
│ │   Other                            FhlbAdvancesAndOtherBorrowingsAdditionalInformationDetail     20         │ │
│ │   Other                            EmployeeBenefitPlansAdditionalInformationDetail               2          │ │
│ │   Other                            IncomeTaxesProvisionForIncomeTaxesDetail                      10         │ │
│ │   Other                            IncomeTaxesSummaryOfTheSourcesOfDifferencesBetweenIncomeTa…   15         │ │
│ │   Other                            IncomeTaxesNetDeferredTaxAssetAndLiabilitiesDetail            21         │ │
│ │   Other                            IncomeTaxesAdditionalInformationDetail                        28         │ │
│ │   Disclosures                      DisclosureCommitmentsAndContingenciesSummaryOfContractAmou…   17         │ │
│ │   Other                            CommitmentsAndContingenciesAdditionalInformationDetail        9          │ │
│ │   Disclosures                      EmployeeStockOwnershipPlanEmployeeStockOwnershipPlanEsopDi…   6          │ │
│ │   Disclosures                      EmployeeStockOwnershipPlanEmployeeStockOwnershipPlanEsopDi…   2          │ │
│ │   Other                            EmployeeStockOwnershipPlanAdditionalInformationDetail         21         │ │
│ │   Other                            RelatedPartyTransactionsSummaryOfLoansToDirectorsExecutive…   5          │ │
│ │   Other                            RelatedPartyTransactionsAdditionalInformationDetail           9          │ │
│ │   Other                            FairValueSummaryOfAssetsMeasuredAtFairValueOnARecurringBas…   22         │ │
│ │   Other                            FairValueScheduleOfQuantitativeInformationAboutNonrecurrin…   20         │ │
│ │   Other                            FairValueSummaryOfCarryingValuesAndEstimatedFairValuesOfFi…   26         │ │
│ │   Other                            FairValueAdditionalInformationDetail                          2          │ │
│ │   Other                            EquityAndRegulatoryMattersScheduleOfBanksActualAndRequired…   25         │ │
│ │   Disclosures                      DisclosureEquityAndRegulatoryMattersAdditionalInformationD…   5          │ │
│ │   Other                            DeferredCompensationAdditionalInformationDetail               14         │ │
│ │   Disclosures                      DisclosureEarningsLossPerShareEpsAdditionalInformationDeta…   2          │ │
│ │   Disclosures                      DisclosureEarningsLossPerShareEpsEarningsPerCommonShareDet…   10         │ │
│ │   Disclosures                      DisclosureEarningsLossPerShareEpsScheduleOfEarningsPerShar…   2          │ │
│ │   Other                            StockBasedCompensationAdditionalInformationDetail             19         │ │
│ │   Other                            StockBasedCompensationSummaryOfAssumptionsUsedInEstimating…   6          │ │
│ │   Other                            StockBasedCompensationSummaryOfStockOptionActivityDetail      24         │ │
│ │   Other                            StockBasedCompensationSummaryOfNonvestedStockOptionActivit…   9          │ │
│ │   Other                            StockBasedCompensationSummaryOfNonvestedStockOptionActivit…   9          │ │
│ │   Other                            StockBasedCompensationSummaryOfRestrictedStockUnitActivity…   9          │ │
│ │   Other                            StockBasedCompensationSummaryOfRestrictedStockUnitActivity…   13         │ │
│ │   Disclosures                      DisclosureParentCompanyOnlyFinancialStatementsSummaryOfCon…   56         │ │
│ │                                                                                                             │ │
│ │      Facts Summary                                                                                          │ │
│ │                                                                                                             │ │

# Another example for 13F-HR

In [23]:
filings = get_filings(form = '13F-HR')
filings

╭────────────────────────────────────────────────── SEC Filings ──────────────────────────────────────────────────╮
│                                                                                                                 │
│    Form              CIK   Ticker   Company                                 Filing Date   Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    13F-HR        1828064            AMIRAL GESTION                          2025-09-15    0001828064-25-0000…   │
│    13F-HR        1828064            AMIRAL GESTION                          2025-09-15    0001828064-25-0000…   │
│    13F-HR/A      1828064            AMIRAL GESTION                          2025-09-15    0001828064-25-0000…   │
│    13F-HR/A      1828064            AMIRAL GESTION                          2025-09-15    0001828064-25-0000…   │
│    13F-HR/A      1846503            Arthedge Capital Management, LLC        2025-09-15    0001214659-25-0137…   │
│    13F-HR/A       884546            CHARLES SCHWAB INVESTMENT MANAGEMENT…   2025-09-15    0001752724-25-2150…   │
│    13F-HR/A      1415912            Migdal Insurance & Financial Holding…   2025-09-15    0001178913-25-0033…   │
│    13F-HR/A      1722641            Valeo Financial Advisors, LLC           2025-09-12    0001722641-25-0000…   │
│    13F-HR        1726041            Milestones Private Investment Adviso…   2025-09-11    0001085146-25-0057…   │
│    13F-HR        1673633            Silicon Valley Capital Partners         2025-09-11    0001398344-25-0180…   │
│    13F-HR/A      1817646            L1 Capital Pty Ltd                      2025-09-11    0001085146-25-0057…   │
│    13F-HR        1780507            WT Wealth Management                    2025-09-10    0001780507-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR/A      1601407            Troy Asset Management Ltd               2025-09-10    0001601407-25-0000…   │
│    13F-HR        2085256            Cambridge Financial Group, LLC          2025-09-09    0001214659-25-0135…   │
│    13F-HR        2085256            Cambridge Financial Group, LLC          2025-09-09    0001214659-25-0135…   │
│    13F-HR        2085256            Cambridge Financial Group, LLC          2025-09-09    0001214659-25-0135…   │
│    13F-HR        2085256            Cambridge Financial Group, LLC          2025-09-09    0001214659-25-0135…   │
│    13F-HR        2085256            Cambridge Financial Group, LLC          2025-09-09    0001214659-25-0135…   │
│    13F-HR        2085256            Cambridge Financial Group, LLC          2025-09-09    0001214659-25-0135…   │
│    13F-HR        2085256            Cambridge Financial Group, LLC          2025-09-09    0001214659-25-0135…   │
│    13F-HR        2045735            NWF Advisory Services Inc.              2025-09-09    0001667731-25-0012…   │
│    13F-HR/A      2056095            Banque Transatlantique SA               2025-09-09    0000945621-25-0008…   │
│    13F-HR        2009486            Alternative Investment Advisors, LLC.   2025-09-08    0001172661-25-0041…   │
│    13F-HR        2009486            Alternative Investment Advisors, LLC.   2025-09-08    0001172661-25-0041…   │
│    13F-HR        2009486            Alternative Investment Advisors, LLC.   2025-09-08    0001172661-25-0041…   │
│    13F-HR        1954782            Hoxton Planning & Management, LLC       2025-09-08    0001954782-25-0000…   │
│                                                                                                                 │
│                                                                                                                 │
│                                                                                                                 │
│ Showing 1 to 50 of 26,328 filings. Page using ← prev() and next() →                                             │
╰───────────────────────────────── SEC Filings between 2025-01-02 and 2025-09-15 ─────────────────────────────────╯

In [24]:
filing = filings[0]
filing

╭──────────────── Form 13F-HR AMIRAL GESTION [1828064]  ────────────────╮
│                                                                       │
│   Accession Number       Filing Date   Period of Report   Documents   │
│  ───────────────────────────────────────────────────────────────────  │
│   0001828064-25-000004   2025-09-15    2025-03-31         2           │
│                                                                       │
│                                                                       │
╰───── Initial quarterly holdings report by institutional managers ─────╯

# Download the report

In [25]:
report = filing.obj()
report

╭──────────────────────── 13F-HR Holding Report for AMIRAL GESTION for period 2025-03-31 ─────────────────────────╮
│                                                                                                                 │
│                   Investment                                                                                    │
│   Report Period   Manager             Signed By           Holdings   Value      Accession Number   Filed        │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   2025-03-31      AMIRAL GESTION      Komilikis Nicolas   27         $181,709   0001828064-25-0…   2025-09-15   │
│                                                                                                                 │
│                                                                                                                 │
│        Issuer                       Class          Cusip       Ticker   Value     Type     Shares    Put/Call   │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│   0    ADOBE INC.                   Common Stock   00724F101   ADBE     $21,907   Shares   57,119               │
│   1    ALPHABET INC.                Common Stock   02079K305   GOOGL    $21,816   Shares   141,079              │
│   2    NVR, Inc.                    Common Stock   62944T105   NVR      $18,278   Shares   2,523                │
│   3    META PLATFORMS, INC.         Common Stock   30303M102   META     $17,249   Shares   29,927               │
│   4    Pepsico, Inc.                Common Stock   713448108   PEP      $16,129   Shares   107,568              │
│   5    MICROSOFT CORPORATION        Common Stock   594918104   MSFT     $13,630   Shares   36,310               │
│   6    BROWN-FORMAN CORPORATION     Common Stock   115637209   BFB      $13,043   Shares   384,306              │
│   7    PAYPAL HOLDINGS, INC.        Common Stock   70450Y103   PYPL     $8,745    Shares   134,020              │
│   8    EDWARDS LIFESCIENCES         Common Stock   28176E108   EW       $7,731    Shares   106,670              │
│        CORPORATION                                                                                              │
│   9    PINDUODUO INC.               ADR            722304102   PDD      $7,042    Shares   59,500               │
│   10   SEA LIMITED                  ADR            81141R100   SE       $5,220    Shares   40,000               │
│   11   PAYLOCITY HOLDING            Common Stock   70438V106   PCTY     $5,038    Shares   26,890               │
│        CORPORATION                                                                                              │
│   12   THE COCA-COLA COMPANY        Common Stock   191216100   KO       $4,886    Shares   68,221               │
│   13   ALLEGION PUBLIC LIMITED      Common Stock   G0176J109   ALLE     $4,144    Shares   31,764               │
│        COMPANY                                                                                                  │
│   14   AIRBNB, INC.                 Common Stock   009066101   ABNB     $2,915    Shares   24,400               │
│   15   Stantec Inc.                 Common Stock   85472N109   STN      $2,303    Shares   27,783               │
│   16   COCA-COLA CONSOLIDATED,      Common Stock   191098102   COKE     $2,276    Shares   1,686                │
│        INC.                                                                                                     │
│   17   BEACON ROOFING SUPPLY,       Common Stock   073685109   BECN     $2,251    Shares   18,200               │
│        INC.                                                                                                     │
│   18   CARLISLE COMPANIES           Common Stock   142339100   CSL      $2,009    Shares   5,900                │
│        INCORPORATED                                                                                             │
│   19   WESCO INTERNATIONAL, INC.    Common Stock   95082P105   WCC      $1,770    Shares   11,400               │
│   20   BOOKING HOLDINGS INC.        Common Stock   09857L108   BKNG     $1,152    Shares   250                  │
│   21   SPOTIFY TECHNOLOGY S.A.      Common Stock   L8681T102   SPOT     $633      Shares   1,150                │
│   22   GDS HOLDINGS LIMITED         ADR            36165L108   GDS      $456      Shares   18,000               │
│   23   FACTSET RESEARCH SYSTEMS     Common Stock   303075105   FDS      $455      Shares   1,000                │
│        INC.                                                                                                     │
│   24   HUYA Inc.                    ADR            44852D108   HUYA     $321      Shares   100,000              │
│   25   MakeMyTrip Limited           Common Stock   V5633W109   MMYT     $283      Shares   2,890                │
│   26   Full Truck Alliance Co Ltd   ADR            35969L108   YMM      $27       Shares   2,118                │
│                                                                                                                 │
╰──────────────────────── 13F-HR Holding Report for AMIRAL GESTION for period 2025-03-31 ─────────────────────────╯

# Check that if a specific report has a info table.

In [26]:
report.has_infotable()

True

# Access to that table

In [27]:
report.infotable

,Issuer,Class,Cusip,Value,SharesPrnAmount,Type,PutCall,InvestmentDiscretion,SoleVoting,SharedVoting,NonVoting,Ticker
0,ADOBE INC.,Common Stock,00724F101,21907,57119,Shares,,SOLE,57119,0,0,ADBE
1,"AIRBNB, INC.",Common Stock,009066101,2915,24400,Shares,,SOLE,24400,0,0,ABNB
2,ALLEGION PUBLIC LIMITED COMPANY,Common Stock,G0176J109,4144,31764,Shares,,SOLE,31764,0,0,ALLE
3,ALPHABET INC.,Common Stock,02079K305,21816,141079,Shares,,SOLE,141079,0,0,GOOGL
4,"BEACON ROOFING SUPPLY, INC.",Common Stock,073685109,2251,18200,Shares,,SOLE,18200,0,0,BECN
5,BOOKING HOLDINGS INC.,Common Stock,09857L108,1152,250,Shares,,SOLE,250,0,0,BKNG
6,BROWN-FORMAN CORPORATION,Common Stock,115637209,13043,384306,Shares,,SOLE,384306,0,0,BFB
7,CARLISLE COMPANIES INCORPORATED,Common Stock,142339100,2009,5900,Shares,,SOLE,5900,0,0,CSL
8,"COCA-COLA CONSOLIDATED, INC.",Common Stock,191098102,2276,1686,Shares,,SOLE,1686,0,0,COKE
9,EDWARDS LIFESCIENCES CORPORATION,Common Stock,28176E108,7731,106670,Shares,,SOLE,106670,0,0,EW
10,FACTSET RESEARCH SYSTEMS INC.,Common Stock,303075105,455,1000,Shares,,SOLE,1000,0,0,FDS
11,Full Truck Alliance Co Ltd,ADR,35969L108,27,2118,Shares,,SOLE,2118,0,0,YMM
12,GDS HOLDINGS LIMITED,ADR,36165L108,456,18000,Shares,,SOLE,18000,0,0,GDS
13,HUYA Inc.,ADR,44852D108,321,100000,Shares,,SOLE,100000,0,0,HUYA
14,"META PLATFORMS, INC.",Common Stock,30303M102,17249,29927,Shares,,SOLE,29927,0,0,META
15,MICROSOFT CORPORATION,Common Stock,594918104,13630,36310,Shares,,SOLE,36310,0,0,MSFT
16,MakeMyTrip Limited,Common Stock,V5633W109,283,2890,Shares,,SOLE,2890,0,0,MMYT
17,"NVR, Inc.",Common Stock,62944T105,18278,2523,Shares,,SOLE,2523,0,0,NVR
18,PAYLOCITY HOLDING CORPORATION,Common Stock,70438V106,5038,26890,Shares,,SOLE,26890,0,0,PCTY
19,"PAYPAL HOLDINGS, INC.",Common Stock,70450Y103,8745,134020,Shares,,SOLE,134020,0,0,PYPL
20,PINDUODUO INC.,ADR,722304102,7042,59500,Shares,,SOLE,59500,0,0,PDD
21,"Pepsico, Inc.",Common Stock,713448108,16129,107568,Shares,,SOLE,107568,0,0,PEP
22,SEA LIMITED,ADR,81141R100,5220,40000,Shares,,SOLE,40000,0,0,SE
23,SPOTIFY TECHNOLOGY S.A.,Common Stock,L8681T102,633,1150,Shares,,SOLE,1150,0,0,SPOT
24,Stantec Inc.,Common Stock,85472N109,2303,27783,Shares,,SOLE,27783,0,0,STN
25,THE COCA-COLA COMPANY,Common Stock,191216100,4886,68221,Shares,,SOLE,68221,0,0,KO
26,"WESCO INTERNATIONAL, INC.",Common Stock,95082P105,1770,11400,Shares,,SOLE,11400,0,0,WCC